/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scanTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reconcileScans"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/orders/{id}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void a refund's share of an order's tickets (internal; commerce only) */
        post: operations["refundTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/orders/{id}/redeliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-send a completed order's tickets to the address on file (internal; back office only) */
        post: operations["redeliverOrderTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/voided-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Voided ticket ids — refunded AND exchanged — for the authenticated device's organizer. Both are refused at a live gate for the same class of reason, and an exchanged ticket is the sharper offline case: its replacement is live elsewhere, so admitting the original admits the exchange twice.
         *     The organizer is taken from the enrolled device token and NEVER from the request. There is no organizer parameter, which is what stops a caller choosing whose revocations to read.
         */
        get: operations["listVoidedTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{ref}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{ref}/tickets/{ticket}/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Requires a live signature minted by GET /orders/{ref}/tickets (ai-review S2). The bundle hands out a fresh, short-lived URL per ticket on every load; a link that outlives its page answers 404, and so does a forged one. The two are deliberately indistinguishable — a distinct status would tell someone holding a dead link that the ticket behind it exists.
         *     The order ref itself remains the bundle's bearer credential. Forwarding "here are your tickets" is a feature; what this bounds is the IMAGE URL, which is what ends up in a screenshot, a referrer header or a proxy log.
         */
        get: operations["getTicketQR"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        TicketRedeliveryCreate: {
            /** Format: uuid */
            organizer_id: string;
        };
        TicketRedelivery: {
            /** Format: uuid */
            order_id: string;
            ticket_count: number;
            replay: boolean;
        };
        TicketRefundCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            refund_id: string;
            quantity: number;
        };
        TicketRefund: {
            ticket_ids: string[];
            replay: boolean;
        };
        ScanRequest: {
            qr_payload: string;
            occurrence_id?: string;
            occurred_at?: string;
            /** @enum {string} */
            direction?: "entry" | "exit";
        };
        ScanAccepted: {
            /** @enum {string} */
            decision: "accepted";
            /** Format: date-time */
            scanned_at: string;
            replay?: boolean;
        };
        ReconcileRequest: {
            occurrences: components["schemas"]["ReconcileOccurrence"][];
        };
        ReconcileOccurrence: {
            qr_payload: string;
            occurrence_id: string;
            occurred_at: string;
            event_type?: string;
        };
        ReconcileResponse: {
            results: components["schemas"]["ReconcileResult"][];
        };
        ReconcileResult: {
            occurrence_id: string;
            /** @enum {string} */
            result: "recorded" | "conflict" | "synced" | "rejected";
            /** Format: date-time */
            occurred_at?: string;
            skew_flagged?: boolean;
        };
        VoidedTicketFeed: {
            ticket_ids: string[];
            next_cursor: string | null;
        };
        ScanRejected: {
            /** @enum {string} */
            decision: "rejected";
            reason: string;
            /** Format: date-time */
            original_scan_at?: string;
        };
        LifecycleEvent: {
            /** Format: uuid */
            id: string;
            type: string;
            /** Format: int64 */
            sequence?: number;
            /** Format: date-time */
            occurred_at: string;
        };
        Ticket: {
            /** Format: uuid */
            ticket_id: string;
            qr_payload: string;
            /** Format: date-time */
            issued_at: string;
            history: components["schemas"]["LifecycleEvent"][];
            qr_url: string;
        };
        TicketBundle: {
            /** Format: uuid */
            order_ref: string;
            tickets: components["schemas"]["Ticket"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Ref: string;
        Id: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scanTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanAccepted"];
                };
            };
            /**
             * @description The scanner device is not enrolled, or its enrolment was revoked (ai-review S1). Deliberately a DIFFERENT status from the 422 an invalid ticket credential gets: a gate app has to tell "this phone is not paired" from "turn this person away", and collapsing them sends an operator to the wrong problem at the worst possible moment.
             *     Unenrolled and revoked are one answer, though — that difference is for an operator reading a log, not for whoever is holding the phone.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rejected: already redeemed, or refused by the integrity degraded mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRejected"];
                };
            };
            /** @description Invalid credential */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRejected"];
                };
            };
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    reconcileScans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileRequest"];
            };
        };
        responses: {
            /** @description Per-occurrence reconciliation results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResponse"];
                };
            };
            /**
             * @description The scanner device is not enrolled, or its enrolment was revoked (ai-review S1). Deliberately a DIFFERENT status from the 422 an invalid ticket credential gets: a gate app has to tell "this phone is not paired" from "turn this person away", and collapsing them sends an operator to the wrong problem at the worst possible moment.
             *     Unenrolled and revoked are one answer, though — that difference is for an operator reading a log, not for whoever is holding the phone.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Malformed envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    refundTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRefundCreate"];
            };
        };
        responses: {
            /** @description Tickets voided (or replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRefund"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    redeliverOrderTickets: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRedeliveryCreate"];
            };
        };
        responses: {
            /** @description Tickets re-sent (or replay of an earlier request) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRedelivery"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listVoidedTickets: {
        parameters: {
            query?: {
                /** @description The opaque cursor from the previous page. Absent means the first page. A cursor is bound to the organizer it was issued for: one presented by a different organizer is a 400, never a silently shifted or empty page. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of voided ticket ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoidedTicketFeed"];
                };
            };
            400: components["responses"]["Error"];
            /** @description The scanner device is not enrolled, or its enrolment was revoked — the same answer, and the same reasoning, as the scan routes. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    getTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: components["parameters"]["Ref"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketBundle"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getTicketQR: {
        parameters: {
            query: {
                /** @description Signature expiry, as Unix seconds. */
                exp: string;
                /** @description base64url HMAC over the order ref, the ticket id and the expiry. */
                sig: string;
            };
            header?: never;
            path: {
                ref: components["parameters"]["Ref"];
                ticket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG QR artwork */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
}
