/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a general-admission venue */
        post: operations["createVenue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an event (localizable content) */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a dated performance (draft)
         * @description A performance is the catalog's first dated slot (ADR-005): a datable, admission-granting offer. Its shape deliberately carries no concert-specific fields so festival days and park operating days fit the same machinery later.
         */
        post: operations["createPerformance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performances/{performanceId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a performance (idempotent)
         * @description Flips draft to published and emits the platform.catalog.performance.published domain event at least once while it is owed (envelope id is deterministic per publication, so retried or raced emissions de-duplicate). Publishing an already-published performance returns 200 without re-emitting. Publishing a performance with no ticket type is a 409 — the publication event and public visibility must never disagree.
         */
        post: operations["publishPerformance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performances/{performanceId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a published performance (idempotent)
         * @description Flips published to archived and emits the platform.catalog.performance.archived domain event at least once while it is owed. Retried or raced emissions de-duplicate at the stream using a deterministic envelope id. Any publication event still owed is emitted before the archive event. Re-archiving returns 200; archiving a draft returns 409.
         */
        post: operations["archivePerformance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performances/{performanceId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a published slot (weather closure; idempotent)
         * @description Sets the orthogonal closure attribute to closed and emits platform.catalog.performance.closed at least once while owed (spike §Case 3). Closure is reversible (see reopen) and does not change the draft/published/archived lifecycle. Closing an already-closed slot returns 200 without a new transition. Only published slots can close.
         */
        post: operations["closeSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/performances/{performanceId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen a closed slot (idempotent)
         * @description Sets the closure attribute back to open and emits platform.catalog.performance.reopened at least once while owed. Reopening an already-open slot returns 200 without a new transition.
         */
        post: operations["reopenSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a localized series for one event */
        post: operations["createSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{seriesId}/performances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach an ordered draft slot to a series */
        post: operations["attachPerformanceToSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{seriesId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically publish every slot in the series */
        post: operations["publishSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{seriesId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically archive every published slot in the series */
        post: operations["archiveSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a localized season */
        post: operations["createSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a series to a season */
        post: operations["attachSeriesToSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{seasonId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a standalone event to a season */
        post: operations["attachEventToSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/festivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a localized shared-capacity festival */
        post: operations["createFestival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/festivals/{festivalId}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a draft festival day to the shared-capacity festival */
        post: operations["attachDayToFestival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/festivals/{festivalId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically publish the festival and every member day */
        post: operations["publishFestival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/festivals/{festivalId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically archive the festival and every member day */
        post: operations["archiveFestival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a ticket type with a price */
        post: operations["createTicketType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated storefront list read (minutes tier)
         * @description Everything the storefront list page needs in one call (ADR-004 rule 3). Only events with at least one publicly listable performance appear — published AND carrying at least one ticket type (no sellable offer, no listing). An event with several such performances appears once, listing each slot. Cache-Control: public, max-age=300, s-maxage=300 (minutes tier).
         */
        get: operations["listPublicEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated storefront detail read (minutes tier)
         * @description Everything the storefront detail page needs in one call, including ticket types and prices. 404 unless the event has at least one publicly listable performance (published + priced). Cache-Control: public, max-age=300, s-maxage=300 (minutes tier).
         */
        get: operations["getPublicEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/seasons/{seasonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated public season detail (minutes tier)
         * @description One call returns the localized season and its deduplicated public event details, retaining series framing. Program membership changes on the same editorial cadence as event detail, so it uses that five-minute tier: Cache-Control: public, max-age=300, s-maxage=300.
         */
        get: operations["getPublicSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/festivals/{festivalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated public festival detail (minutes tier)
         * @description One call returns the localized festival and all publicly listable festival days drawing on its shared capacity. Festival programming uses the ADR-004 minutes tier: Cache-Control: public, max-age=300, s-maxage=300.
         */
        get: operations["getPublicFestival"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This contract, as committed (ADR-009) */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /** @description Locale-keyed text; adding a locale is data, not a schema change (TKT-36) */
        LocalizedString: {
            [key: string]: string;
        };
        /** @description Integer minor units + ISO-4217 code (ADR-001); no floats, ever */
        Money: {
            /** Format: int64 */
            amount: number;
            currency: string;
        };
        VenueCreate: {
            /** Format: uuid */
            organizer_id: string;
            name: string;
            /** Format: int32 */
            ga_capacity: number;
        };
        Venue: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: string;
            /** Format: int32 */
            ga_capacity: number;
            /** Format: date-time */
            created_at: string;
        };
        EventCreate: {
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
            description?: components["schemas"]["LocalizedString"];
        };
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
            description?: components["schemas"]["LocalizedString"];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description The dated-slot kind (ADR-005 amendment / US-009). 'performance' carries starts_at; 'festival_day'/'operating_day' carry the operating window.
         * @enum {string}
         */
        SlotKind: "performance" | "festival_day" | "operating_day";
        /** @description How many admissions one entitlement grants on the slot (spike §Case 1). 'single' is the performance case; 'count_limited' requires max_entries. */
        ReEntryPolicy: {
            /** @enum {string} */
            mode: "single" | "multi" | "count_limited";
            /** Format: int32 */
            max_entries?: number | null;
            requires_exit: boolean;
        };
        /** @description Weather-closure state (spike §Case 3), orthogonal to the draft/published/archived lifecycle. A closed slot is still published. */
        Closure: {
            /** @enum {string} */
            status: "open" | "closed";
            /** Format: date-time */
            closed_at?: string | null;
            reason?: string | null;
        };
        /** @description Optional operator-supplied reason for the closure */
        SlotCloseRequest: {
            reason?: string;
        };
        /** @description Creates a dated slot in draft. kind defaults to 'performance' (which requires starts_at); 'festival_day'/'operating_day' require the operating window (operating_date + opens_at + closes_at). re_entry defaults to single-entry. */
        PerformanceCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            venue_id: string;
            kind?: components["schemas"]["SlotKind"];
            /**
             * Format: date-time
             * @description Instant for kind 'performance'; omit for day kinds
             */
            starts_at?: string;
            /**
             * Format: date
             * @description Local operating date for day kinds
             */
            operating_date?: string;
            /** @description Local opening time-of-day (HH:MM) for day kinds */
            opens_at?: string;
            /** @description Local closing time-of-day (HH:MM); < opens_at spans midnight */
            closes_at?: string;
            /** @description IANA zone name, e.g. Europe/Paris */
            timezone: string;
            re_entry?: components["schemas"]["ReEntryPolicy"];
        };
        Performance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            venue_id: string;
            kind: components["schemas"]["SlotKind"];
            /**
             * Format: date-time
             * @description Present for kind 'performance'; absent for day kinds
             */
            starts_at?: string;
            /** Format: date */
            operating_date?: string;
            opens_at?: string;
            closes_at?: string;
            timezone: string;
            re_entry: components["schemas"]["ReEntryPolicy"];
            closure: components["schemas"]["Closure"];
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            /** Format: date-time */
            published_at?: string;
            /** Format: date-time */
            archived_at?: string | null;
            /**
             * Format: uuid
             * @description Festival capacity-group id for grouped festival days
             */
            capacity_group_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        TicketTypeCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            performance_id: string;
            name: components["schemas"]["LocalizedString"];
            price: components["schemas"]["Money"];
        };
        TicketType: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            performance_id: string;
            name: components["schemas"]["LocalizedString"];
            price: components["schemas"]["Money"];
            /** Format: date-time */
            created_at: string;
        };
        SeriesCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            event_id: string;
            name: components["schemas"]["LocalizedString"];
        };
        SeriesPerformanceAttach: {
            /** Format: uuid */
            performance_id: string;
            /** Format: int32 */
            position: number;
        };
        SeriesMember: {
            /** Format: uuid */
            performance_id: string;
            /** Format: int32 */
            position: number;
        };
        Series: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            event_id: string;
            name: components["schemas"]["LocalizedString"];
            members: components["schemas"]["SeriesMember"][];
            /** Format: date-time */
            created_at: string;
        };
        SeriesLifecycleResult: {
            /** Format: uuid */
            series_id: string;
            performances: components["schemas"]["Performance"][];
        };
        SeriesTransitionConflict: {
            error: string;
            reason: string;
            /** Format: uuid */
            blocking_performance_id?: string;
        };
        SeasonCreate: {
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
        };
        SeasonSeriesAttach: {
            /** Format: uuid */
            series_id: string;
        };
        SeasonEventAttach: {
            /** Format: uuid */
            event_id: string;
        };
        Season: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
            series_ids: string[];
            event_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        FestivalCreate: {
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
            /** Format: int32 */
            shared_capacity: number;
        };
        FestivalDayAttach: {
            /** Format: uuid */
            performance_id: string;
        };
        Festival: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: components["schemas"]["LocalizedString"];
            /** Format: int32 */
            shared_capacity: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            member_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        FestivalLifecycleResult: {
            /** Format: uuid */
            festival_id: string;
            performances: components["schemas"]["Performance"][];
        };
        PublicEventList: {
            events: components["schemas"]["PublicEventSummary"][];
        };
        PublicEventSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            performances: components["schemas"]["PublicPerformanceSummary"][];
        };
        PublicPerformanceSummary: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            starts_at: string;
            timezone: string;
            venue_name: string;
            from_price: components["schemas"]["Money"];
        };
        PublicEventDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: string;
            description?: string;
            series: components["schemas"]["PublicSeriesContext"][];
            performances: components["schemas"]["PublicPerformanceDetail"][];
        };
        PublicPerformanceDetail: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            starts_at: string;
            timezone: string;
            venue: components["schemas"]["PublicVenue"];
            ticket_types: components["schemas"]["PublicTicketType"][];
        };
        PublicSeriesContext: {
            /** Format: uuid */
            id: string;
            name: string;
            performance_ids: string[];
        };
        PublicSeasonDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: string;
            events: components["schemas"]["PublicEventDetail"][];
        };
        PublicFestivalDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizer_id: string;
            name: string;
            days: components["schemas"]["PublicPerformanceDetail"][];
        };
        PublicVenue: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        PublicTicketType: {
            /** Format: uuid */
            id: string;
            name: string;
            price: components["schemas"]["Money"];
        };
    };
    responses: {
        /** @description Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Referenced entity does not exist (or is not published, on public reads) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description BCP-47 primary subtag; supported set is data, not schema (TKT-36) */
        Locale: string;
        PerformanceId: string;
        EventId: string;
        SeriesId: string;
        SeasonId: string;
        FestivalId: string;
    };
    requestBodies: never;
    headers: {
        /** @description ADR-004 volatility tier, explicit on every public read */
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createVenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueCreate"];
            };
        };
        responses: {
            /** @description Venue created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Event created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformanceCreate"];
            };
        };
        responses: {
            /** @description Performance created in draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    publishPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performanceId: components["parameters"]["PerformanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Performance is published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description No sellable offer, or archived performances cannot be re-published */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    archivePerformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performanceId: components["parameters"]["PerformanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Performance is archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Draft performances cannot be archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    closeSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performanceId: components["parameters"]["PerformanceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SlotCloseRequest"];
            };
        };
        responses: {
            /** @description Slot is closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Only published slots can be closed, or a prior closure event is still owed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reopenSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performanceId: components["parameters"]["PerformanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot is open */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Performance"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Only published slots can be reopened, or a prior closure event is still owed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createSeries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesCreate"];
            };
        };
        responses: {
            /** @description Series created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    attachPerformanceToSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesPerformanceAttach"];
            };
        };
        responses: {
            /** @description Updated series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Slot already belongs to a series, position is occupied, or membership is frozen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    publishSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series members are published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesLifecycleResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Empty series or a member cannot publish */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesTransitionConflict"];
                };
            };
        };
    };
    archiveSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series members are archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesLifecycleResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Empty series, draft member, or member with an owed closure event */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesTransitionConflict"];
                };
            };
        };
    };
    createSeason: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Season created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Season"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    attachSeriesToSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: components["parameters"]["SeasonId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonSeriesAttach"];
            };
        };
        responses: {
            /** @description Updated season */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Season"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Duplicate membership */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    attachEventToSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: components["parameters"]["SeasonId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonEventAttach"];
            };
        };
        responses: {
            /** @description Updated season */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Season"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Duplicate membership */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createFestival: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FestivalCreate"];
            };
        };
        responses: {
            /** @description Festival created in draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Festival"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    attachDayToFestival: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                festivalId: components["parameters"]["FestivalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FestivalDayAttach"];
            };
        };
        responses: {
            /** @description Updated festival */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Festival"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Wrong slot kind, existing group, frozen day, or launched festival */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    publishFestival: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                festivalId: components["parameters"]["FestivalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Festival and member days are published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FestivalLifecycleResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Empty festival or a member cannot publish */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesTransitionConflict"];
                };
            };
        };
    };
    archiveFestival: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                festivalId: components["parameters"]["FestivalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Festival and member days are archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FestivalLifecycleResult"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Empty festival, draft member, or member with an owed closure event */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesTransitionConflict"];
                };
            };
        };
    };
    createTicketType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketTypeCreate"];
            };
        };
        responses: {
            /** @description Ticket type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketType"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listPublicEvents: {
        parameters: {
            query: {
                /** @description BCP-47 primary subtag; supported set is data, not schema (TKT-36) */
                locale: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published events, localized */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventList"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPublicEvent: {
        parameters: {
            query: {
                /** @description BCP-47 primary subtag; supported set is data, not schema (TKT-36) */
                locale: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published event detail, localized */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicSeason: {
        parameters: {
            query: {
                /** @description BCP-47 primary subtag; supported set is data, not schema (TKT-36) */
                locale: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                seasonId: components["parameters"]["SeasonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published season detail, localized */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSeasonDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicFestival: {
        parameters: {
            query: {
                /** @description BCP-47 primary subtag; supported set is data, not schema (TKT-36) */
                locale: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                festivalId: components["parameters"]["FestivalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published festival detail, localized */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicFestivalDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document, byte-identical to the repo file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
}
