/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an optional customer account (TKT-220)
         * @description Registers a buyer account. Commerce owns orders and buyer_pii, so the buyer principal lives here rather than in catalog, on the stateless gateway, or in a sixth service — ADR-049 records the decision and why ADR-042's reasoning for putting STAFF in catalog does not transplant to a customer, who administers nothing.
         *     This operation is PUBLIC and carries no credential. Registration is open to anyone by definition, and the storefront that renders the form holds no service token at all — giving it one to reach an /internal/ endpoint would put a credential inside a process that serves anonymous internet traffic. ADR-043's rule is what places it here: declared contract operations are the service's public surface, inline X-Internal-Token checks guard /internal/.
         *     An address that is already registered answers 409. That deliberately discloses whether an address holds an account — an unauthenticated, unrate-limited membership oracle over the whole customer base. The alternative (answer 201 and mail the owner) is not available: this repo has no mail path, so it would be a lie told to a legitimate buyer rather than a protection. Rate limiting is TKT-224 and is the control that addresses it.
         *     buyer_pii is NOT touched. It is keyed per reservation and rewritten on every checkout — an order-time snapshot, not an identity. Attaching an order to an account is TKT-221.
         */
        post: operations["registerCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in customer's completed purchases, newest first (TKT-222)
         * @description The wallet read. Returns the COMPLETED orders belonging to the customer the `X-Customer-Assertion` header authenticates as, newest first, keyset-paged.
         *     **The path id is a selector, not authority.** The handler compares it with the customer the assertion resolves to and refuses when they differ — the assertion is the only identity commerce has (ADR-049 § TKT-221). A mismatch answers **404**, identical to an id that does not exist: a 403 would confirm that the named customer exists, which is an account-existence oracle reachable by anyone who can register once. Commerce already answers 404 rather than 401 on its internal surface for the same non-disclosure reason (ADR-043).
         *     Paged on `(created_at, id)` DESC, NOT `updated_at`: that column is rewritten by checkout retries, the payment_unknown and confirmation_pending transitions, recovery and the cancellation-refund runner, and a keyset cursor on a mutable key makes rows jump pages. `created_at` also means the thing a buyer expects a purchase list to be sorted by.
         *     Each row carries `guest_order_ref`, which is a BEARER credential for the ticket bundle (ADR-012) — it is here because the wallet's job is to link to the existing ticket page rather than render tickets a second time. The response is `no-store` and the reference must not reach a log.
         *     Naming the adversary (ADR-021): this stops an HTTP caller from reading another customer's purchases. It says nothing about anyone who can read the commerce database.
         */
        get: operations["listCustomerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify customer credentials and return the principal (TKT-220)
         * @description Verifies an email/password pair and returns the principal — customer id and the address in its original spelling. Never any password material.
         *     An unknown address and a wrong password are the SAME answer: the same 401, the same body. They also cost the same, because the unknown-address path still performs one bcrypt comparison against a fixed dummy hash of the production cost. A response that is byte-identical but an order of magnitude faster is still an enumeration oracle.
         *     Public for the same reason as registerCustomer: the sign-in form in front of it is anonymous by construction.
         */
        post: operations["authenticateCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/operational-holds/{id}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff conversion of an operational hold into a purchasable reservation */
        post: operations["convertOperationalHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/group-reservations/{id}/draw-down": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff draw-down of a group/agency reservation into a purchasable reservation */
        post: operations["drawDownGroupReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/orders/{id}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff refund of all or part of a completed order (money leg only) */
        post: operations["refundOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/orders/{id}/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff exchange of a completed order for a different ticket type (settlement only) */
        post: operations["exchangeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/exchanges/{id}/tickets-switched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access reports that an exchange's entitlement switch has committed */
        post: operations["exchangeTicketsSwitched"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/slots/{id}/cancellation-refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund a cancelled event's whole order book, with a per-order outcome */
        post: operations["createCancellationRefundRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/cancellation-refunds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-order outcomes of a cancellation refund run */
        get: operations["getCancellationRefundReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/buyers/{id}/delivery-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeliveryEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            /**
             * @description Machine-readable refusal reason. `seat_taken`: a seated reservation lost seats to a competing claimant (TKT-173). `orphaned_seats`: the selection would strand free seats with no free neighbour (ADR-041, TKT-182).
             * @enum {string}
             */
            code?: "seat_taken" | "orphaned_seats";
            /** @description With `seat_taken`: the requested seats another buyer already holds, sorted — a SUBSET of the request, forwarded verbatim from the inventory transaction that arbitrated. With `orphaned_seats`: the FREE seats the selection would strand — seats the buyer did NOT request, so the subset rule deliberately does not apply to them and a picker must keep them selectable, since adding one is the repair. Never synthesised by commerce: a refusal without a usable identity list is a 502, not a guess. */
            seat_identities?: string[];
        };
        /** @description Exactly one of `quantity` (general admission) or `seat_identities` (reserved seating, TKT-173) — never both, never neither. That XOR is expressed by the property counts rather than a top-level `oneOf`: with two required properties, two optional ones and no additional properties allowed, `minProperties: 3` / `maxProperties: 3` admits exactly one of the alternatives. `oneOf` would be the obvious spelling and is avoided deliberately — the generator turns a top-level union into a json.RawMessage with As…/From… accessors instead of a usable request struct, which is a worse contract bought with a worse API. The handler enforces the same XOR independently; a caller invoking it directly must not be able to slip past the schema. */
        ReservationCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            ticket_type_id: string;
            /**
             * @description The sales channel this purchase is made through, selecting which fee rules apply (TKT-215, ADR-046 §4). An exact opaque string (ADR-024) -- there is no channel registry, and inventing one here would decide TKT-17's story.
             *     OMITTING it is the default/public context, in which only channel-agnostic fee rules are eligible. It is NOT a wildcard: a channel-specific rule never applies to a sale that named no channel.
             *     It reaches catalog's fee resolution and stops there. It is deliberately NOT forwarded to inventory, whose own channel_code is what channel allocations cap consumption against -- propagating it would make a sale start failing with 409 when an allocation is exhausted, on ticket types this change never touched.
             */
            channel_code?: string;
            /** @description General admission: how many. Mutually exclusive with seat_identities. */
            quantity?: number;
            /** @description Reserved seating: exactly which seats, as stable "section/row/seat" identities read from the seat map. Mutually exclusive with quantity. The set is canonicalised (sorted, de-duplicated) by inventory, so [A,B] and [B,A] are the same request under one idempotency key — and the reservation's money follows the CLAIMED seat count, not the length of this array. */
            seat_identities?: string[];
        };
        Reservation: {
            /** Format: uuid */
            reservation_id: string;
            /** Format: uuid */
            hold_id: string;
            /** Format: uuid */
            buyer_id: string;
            /** Format: int64 */
            amount: number;
            currency: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            server_time: string;
            /** @description The seats actually claimed, sorted and de-duplicated — inventory's canonical set, never the request's array (TKT-173). Present on a seated reservation and OMITTED on a general-admission one: absence is the reservation-kind signal, and an empty array would read as a seated claim that holds nothing. It cannot be required, because every existing GA and staff-created reservation response lacks it and the response validator fails closed (ADR-028) — requiring it would turn those valid responses into runtime 500s. */
            seats?: string[];
            /**
             * Format: int64
             * @description The rule-resolved price times quantity, before any fee (TKT-215). `amount` minus `face_value` is exactly the passed-on fee total.
             *     OPTIONAL, like `seats` and for the same reason: every reservation created before this field existed lacks it, and the response validator fails closed (ADR-028), so requiring it would turn those valid responses into runtime 500s. It is absent on a reservation with no fee snapshot -- a pre-TKT-215 row or a staff-created one -- and absence means "this sale had no fee concept", which is a different fact from "its fees totalled nothing".
             */
            face_value?: number;
            /**
             * Format: int64
             * @description The part of `amount` that is fees the buyer pays. Absorbed fees are NOT here and never reach `amount`: they are borne by the organizer out of the face value, and charging them to the buyer would be charging for the organizer's cost. They are recorded in the persisted snapshot because TKT-217 still owes them to a payee.
             */
            passed_on_fees?: number;
            /** @description One entry per fee code that applied, INCLUDING any whose computed amount is zero (ADR-046 §2) -- a code that vanished as a function of price would leave settlement with a payee that is sometimes owed nothing and sometimes absent. A fee code that was considered but had no live rule produces no entry at all. */
            fee_breakdown?: {
                fee_code: string;
                /** @enum {string} */
                basis: "per_ticket_fixed" | "per_order_fixed" | "percentage_bps";
                /** @enum {string} */
                incidence: "passed_on" | "absorbed";
                /** Format: int64 */
                amount: number;
                currency: string;
            }[];
        };
        OperationalConversionCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            ticket_type_id: string;
            quantity: number;
            actor: string;
            reason: string;
        };
        OperationalConversion: {
            /** Format: uuid */
            reservation_id: string;
            /** Format: uuid */
            hold_id: string;
            /** Format: uuid */
            buyer_id: string;
            /** Format: int64 */
            amount: number;
            currency: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            server_time: string;
            source_remaining: number;
        };
        /**
         * @description A customer registration attempt (TKT-220). maxLength on both fields bounds the work an unauthenticated caller can ask for. 72 on the password is bcrypt's hard input limit, past which it silently ignores the tail — so a longer password and its 72-byte prefix would authenticate each other.
         *     Note the limit is not fully expressible here: OpenAPI counts CHARACTERS and bcrypt counts BYTES, so 72 multibyte characters clear this schema and are three times over bcrypt's bound. The store refuses those before it touches the database, uniformly, so the refusal leaks nothing.
         */
        CustomerRegistration: {
            email: string;
            password: string;
        };
        /** @description A customer sign-in attempt (TKT-220). Bounded for the same reason as CustomerRegistration. */
        CustomerCredentials: {
            email: string;
            password: string;
        };
        CustomerOrderPage: {
            orders: components["schemas"]["CustomerOrderSummary"][];
            /** @description The cursor for the next page, or null when this page is the last. REQUIRED and nullable rather than optional: an absent field and an explicit null read the same to a careless client, and "there is no more" is a different fact from "we did not say". */
            next_cursor: string | null;
        };
        CustomerOrderSummary: {
            /** Format: uuid */
            order_id: string;
            /**
             * Format: uuid
             * @description A bearer credential for the ticket bundle (ADR-012). Present so the wallet can LINK to the existing ticket page; never log it.
             */
            guest_order_ref: string;
            /** Format: date-time */
            purchased_at: string;
            quantity: number;
            /** @description Integer minor units (ADR-001). Never a float, never divided here. */
            total_amount: number;
            currency: string;
            /** @description Resolved from catalog in one call per page. Null when catalog cannot name the performance — a row the buyer can still open beats a wallet that will not load. */
            event_name: string | null;
            /** Format: date-time */
            starts_at: string | null;
        };
        /** @description A signed-in buyer. `email` is the address in the spelling the buyer registered with, for display; every lookup goes through the normalized form, which is never exposed. */
        CustomerPrincipal: {
            /** Format: uuid */
            customer_id: string;
            email: string;
            /**
             * @description A commerce-signed, expiring proof that the holder authenticated as this customer, presented on checkout in `X-Customer-Assertion` (TKT-221, ADR-049).
             *     This is a BEARER CREDENTIAL: anyone holding it can attribute a checkout to this customer until it expires. It is returned only to a caller who has just proven the password, and the storefront keeps it server-side inside its in-process session — never in a cookie, a rendered prop, or a log. Its lifetime is deliberately equal to that session's, so "the session is alive" and "the assertion is valid" cannot disagree and strand a buyer at the payment button.
             */
            customer_assertion: string;
        };
        Checkout: {
            /** Format: uuid */
            reservation_id: string;
            name: string;
            email: string;
            payment_token: string;
        };
        OrderResult: {
            /** Format: uuid */
            order_id: string;
            /** Format: uuid */
            guest_order_ref: string;
            /** @enum {string} */
            status: "completed";
        };
        OrderPending: {
            /** Format: uuid */
            order_id: string;
            status: string;
        };
        OrderFailure: {
            /** Format: uuid */
            order_id: string;
            status: string;
            replay?: boolean;
        } & {
            [key: string]: unknown;
        };
        OrderConflict: {
            error: string;
            /** Format: uuid */
            order_id?: string;
            status?: string;
        };
        OrderState: {
            /** Format: uuid */
            order_id: string;
            status: string;
            /**
             * Format: uuid
             * @description The customer account this order belongs to, or null for a guest purchase (TKT-221). REQUIRED and nullable rather than optional: an absent field and an explicit null read the same to a careless client, and "we did not tell you" is not the same fact as "there is no account". Guest is the default and is first-class.
             *     Informational only. This read is PUBLIC and answers for any order id, so the presence of this field is not an ownership check — TKT-222 owns the authenticated, ownership-scoped read.
             */
            customer_id: string | null;
        };
        RefundCreate: {
            /** Format: uuid */
            organizer_id: string;
            quantity: number;
            actor: string;
            reason: string;
        };
        Refund: {
            /** Format: uuid */
            refund_id: string;
            /** Format: uuid */
            order_id: string;
            quantity: number;
            /** Format: int64 */
            amount: number;
            currency: string;
            /** @enum {string} */
            refund_status: "none" | "partial" | "full";
            refunded_quantity: number;
            /** Format: int64 */
            refunded_amount: number;
            replay: boolean;
            tickets_voided: boolean;
            capacity_returned: boolean;
        };
        ExchangeCreate: {
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            target_ticket_type_id: string;
            actor: string;
            reason: string;
        };
        Exchange: {
            /** Format: uuid */
            exchange_id: string;
            /** Format: uuid */
            source_order_id: string;
            /** Format: uuid */
            replacement_order_id: string;
            quantity: number;
            /** Format: int64 */
            source_total: number;
            /** Format: int64 */
            target_total: number;
            /** Format: int64 */
            delta_amount: number;
            currency: string;
            /** @enum {string} */
            status: "switch_pending" | "capacity_pending" | "completed";
            tickets_exchanged: boolean;
            capacity_returned: boolean;
            replay: boolean;
        };
        ExchangeSwitched: {
            /** Format: uuid */
            organizer_id: string;
        };
        ExchangeSwitchResult: {
            /** Format: uuid */
            exchange_id: string;
            tickets_exchanged: boolean;
            capacity_returned: boolean;
        };
        DeliveryEmail: {
            email: string;
        };
        CancellationRefundCreate: {
            /** Format: uuid */
            organizer_id: string;
            actor: string;
            reason: string;
        };
        CancellationRefundRun: {
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            organizer_id: string;
            /** Format: uuid */
            slot_id: string;
            /** @enum {string} */
            status: "pending" | "running" | "completed";
            /** Format: date-time */
            cutoff_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
            replay: boolean;
        };
        CancellationRefundCounts: {
            total: number;
            refunded: number;
            already_refunded: number;
            failed: number;
            pending: number;
        };
        CancellationRefundOutcome: {
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            outcome: "refunded" | "already_refunded" | "failed";
            /** Format: uuid */
            refund_id?: string;
            refunded_quantity: number;
            /** Format: int64 */
            refunded_amount: number;
            currency: string;
            money_refunded: boolean;
            tickets_voided: boolean;
            capacity_returned: boolean;
            failure?: components["schemas"]["CancellationRefundFailure"];
        };
        CancellationRefundFailure: {
            /** @enum {string} */
            code: "no_captured_money" | "not_refundable" | "refund_refused" | "ceiling_moved" | "reversal_outstanding" | "unavailable" | "internal";
            reason: string;
        };
        CancellationRefundReport: {
            run: components["schemas"]["CancellationRefundRun"];
            counts: components["schemas"]["CancellationRefundCounts"];
            incomplete_at_enumeration: number;
            orders: components["schemas"]["CancellationRefundOutcome"][];
            /** Format: uuid */
            next_after_order_id?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        IdempotencyKey: string;
        CustomerAssertion: string;
        /** @description BCP-47 primary subtag; the supported set is data, not schema (TKT-36) */
        Locale: string;
        OrganizerIdQuery: string;
        ReportLimit: number;
        AfterOrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Reserved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Customer-Assertion"?: components["parameters"]["CustomerAssertion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Checkout"];
            };
        };
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResult"];
                };
            };
            /** @description Recovery pending */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPending"];
                };
            };
            400: components["responses"]["Error"];
            /** @description The assertion is absent-but-malformed, forged or expired. NOT downgraded to a guest order: silently dropping a failed attribution would hide it from the buyer, who would then not find the purchase in their account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Declined */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderFailure"];
                };
            };
            /** @description No-side-effect timeout */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderFailure"];
                };
            };
            /** @description Checkout conflict or payment in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderConflict"];
                };
            };
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderState"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    registerCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRegistration"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPrincipal"];
                };
            };
            400: components["responses"]["Error"];
            /** @description The address already holds an account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listCustomerOrders: {
        parameters: {
            query: {
                /** @description BCP-47 primary subtag; the supported set is data, not schema (TKT-36) */
                locale: components["parameters"]["Locale"];
                /** @description The opaque cursor from the previous page. Absent means the first page. */
                after?: string;
            };
            header?: {
                "X-Customer-Assertion"?: components["parameters"]["CustomerAssertion"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the wallet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOrderPage"];
                };
            };
            400: components["responses"]["Error"];
            /** @description The assertion is absent */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such customer — or the assertion names a different one. Deliberately the same answer. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    authenticateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCredentials"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPrincipal"];
                };
            };
            400: components["responses"]["Error"];
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    convertOperationalHold: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationalConversionCreate"];
            };
        };
        responses: {
            /** @description Replayed conversion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalConversion"];
                };
            };
            /** @description Converted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalConversion"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    drawDownGroupReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationalConversionCreate"];
            };
        };
        responses: {
            /** @description Replayed draw-down */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalConversion"];
                };
            };
            /** @description Drawn down */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationalConversion"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    refundOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundCreate"];
            };
        };
        responses: {
            /** @description Refunded (or replay of a completed refund) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    exchangeOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeCreate"];
            };
        };
        responses: {
            /** @description Settled (or replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exchange"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    exchangeTicketsSwitched: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeSwitched"];
            };
        };
        responses: {
            /** @description Switch recorded and old capacity returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeSwitchResult"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    createCancellationRefundRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancellationRefundCreate"];
            };
        };
        responses: {
            /** @description Replay of an identical run request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationRefundRun"];
                };
            };
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationRefundRun"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getCancellationRefundReport: {
        parameters: {
            query: {
                organizer_id: components["parameters"]["OrganizerIdQuery"];
                limit?: components["parameters"]["ReportLimit"];
                after_order_id?: components["parameters"]["AfterOrderId"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed report page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationRefundReport"];
                };
            };
            /** @description Run still enumerating or processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationRefundReport"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getDeliveryEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryEmail"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
