// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CancellationRefundFailureCode.
const (
	CeilingMoved        CancellationRefundFailureCode = "ceiling_moved"
	Internal            CancellationRefundFailureCode = "internal"
	NoCapturedMoney     CancellationRefundFailureCode = "no_captured_money"
	NotRefundable       CancellationRefundFailureCode = "not_refundable"
	RefundRefused       CancellationRefundFailureCode = "refund_refused"
	ReversalOutstanding CancellationRefundFailureCode = "reversal_outstanding"
	Unavailable         CancellationRefundFailureCode = "unavailable"
)

// Valid indicates whether the value is a known member of the CancellationRefundFailureCode enum.
func (e CancellationRefundFailureCode) Valid() bool {
	switch e {
	case CeilingMoved:
		return true
	case Internal:
		return true
	case NoCapturedMoney:
		return true
	case NotRefundable:
		return true
	case RefundRefused:
		return true
	case ReversalOutstanding:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for CancellationRefundOutcomeOutcome.
const (
	AlreadyRefunded CancellationRefundOutcomeOutcome = "already_refunded"
	Failed          CancellationRefundOutcomeOutcome = "failed"
	Refunded        CancellationRefundOutcomeOutcome = "refunded"
)

// Valid indicates whether the value is a known member of the CancellationRefundOutcomeOutcome enum.
func (e CancellationRefundOutcomeOutcome) Valid() bool {
	switch e {
	case AlreadyRefunded:
		return true
	case Failed:
		return true
	case Refunded:
		return true
	default:
		return false
	}
}

// Defines values for CancellationRefundRunStatus.
const (
	CancellationRefundRunStatusCompleted CancellationRefundRunStatus = "completed"
	CancellationRefundRunStatusPending   CancellationRefundRunStatus = "pending"
	CancellationRefundRunStatusRunning   CancellationRefundRunStatus = "running"
)

// Valid indicates whether the value is a known member of the CancellationRefundRunStatus enum.
func (e CancellationRefundRunStatus) Valid() bool {
	switch e {
	case CancellationRefundRunStatusCompleted:
		return true
	case CancellationRefundRunStatusPending:
		return true
	case CancellationRefundRunStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	OrphanedSeats ErrorCode = "orphaned_seats"
	SeatTaken     ErrorCode = "seat_taken"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case OrphanedSeats:
		return true
	case SeatTaken:
		return true
	default:
		return false
	}
}

// Defines values for ExchangeStatus.
const (
	ExchangeStatusCapacityPending ExchangeStatus = "capacity_pending"
	ExchangeStatusCompleted       ExchangeStatus = "completed"
	ExchangeStatusSwitchPending   ExchangeStatus = "switch_pending"
)

// Valid indicates whether the value is a known member of the ExchangeStatus enum.
func (e ExchangeStatus) Valid() bool {
	switch e {
	case ExchangeStatusCapacityPending:
		return true
	case ExchangeStatusCompleted:
		return true
	case ExchangeStatusSwitchPending:
		return true
	default:
		return false
	}
}

// Defines values for OrderResultStatus.
const (
	Completed OrderResultStatus = "completed"
)

// Valid indicates whether the value is a known member of the OrderResultStatus enum.
func (e OrderResultStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	default:
		return false
	}
}

// Defines values for RefundRefundStatus.
const (
	Full    RefundRefundStatus = "full"
	None    RefundRefundStatus = "none"
	Partial RefundRefundStatus = "partial"
)

// Valid indicates whether the value is a known member of the RefundRefundStatus enum.
func (e RefundRefundStatus) Valid() bool {
	switch e {
	case Full:
		return true
	case None:
		return true
	case Partial:
		return true
	default:
		return false
	}
}

// CancellationRefundCounts defines model for CancellationRefundCounts.
type CancellationRefundCounts struct {
	AlreadyRefunded int `json:"already_refunded"`
	Failed          int `json:"failed"`
	Pending         int `json:"pending"`
	Refunded        int `json:"refunded"`
	Total           int `json:"total"`
}

// CancellationRefundCreate defines model for CancellationRefundCreate.
type CancellationRefundCreate struct {
	Actor       string             `json:"actor"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Reason      string             `json:"reason"`
}

// CancellationRefundFailure defines model for CancellationRefundFailure.
type CancellationRefundFailure struct {
	Code   CancellationRefundFailureCode `json:"code"`
	Reason string                        `json:"reason"`
}

// CancellationRefundFailureCode defines model for CancellationRefundFailure.Code.
type CancellationRefundFailureCode string

// CancellationRefundOutcome defines model for CancellationRefundOutcome.
type CancellationRefundOutcome struct {
	CapacityReturned bool                             `json:"capacity_returned"`
	Currency         string                           `json:"currency"`
	Failure          *CancellationRefundFailure       `json:"failure,omitempty"`
	MoneyRefunded    bool                             `json:"money_refunded"`
	OrderId          openapi_types.UUID               `json:"order_id"`
	Outcome          CancellationRefundOutcomeOutcome `json:"outcome"`
	RefundId         *openapi_types.UUID              `json:"refund_id,omitempty"`
	RefundedAmount   int64                            `json:"refunded_amount"`
	RefundedQuantity int                              `json:"refunded_quantity"`
	TicketsVoided    bool                             `json:"tickets_voided"`
}

// CancellationRefundOutcomeOutcome defines model for CancellationRefundOutcome.Outcome.
type CancellationRefundOutcomeOutcome string

// CancellationRefundReport defines model for CancellationRefundReport.
type CancellationRefundReport struct {
	Counts                  CancellationRefundCounts    `json:"counts"`
	IncompleteAtEnumeration int                         `json:"incomplete_at_enumeration"`
	NextAfterOrderId        *openapi_types.UUID         `json:"next_after_order_id,omitempty"`
	Orders                  []CancellationRefundOutcome `json:"orders"`
	Run                     CancellationRefundRun       `json:"run"`
}

// CancellationRefundRun defines model for CancellationRefundRun.
type CancellationRefundRun struct {
	CompletedAt *time.Time                  `json:"completed_at,omitempty"`
	CreatedAt   time.Time                   `json:"created_at"`
	CutoffAt    time.Time                   `json:"cutoff_at"`
	OrganizerId openapi_types.UUID          `json:"organizer_id"`
	Replay      bool                        `json:"replay"`
	RunId       openapi_types.UUID          `json:"run_id"`
	SlotId      openapi_types.UUID          `json:"slot_id"`
	Status      CancellationRefundRunStatus `json:"status"`
}

// CancellationRefundRunStatus defines model for CancellationRefundRun.Status.
type CancellationRefundRunStatus string

// Checkout defines model for Checkout.
type Checkout struct {
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	PaymentToken  string             `json:"payment_token"`
	ReservationId openapi_types.UUID `json:"reservation_id"`
}

// DeliveryEmail defines model for DeliveryEmail.
type DeliveryEmail struct {
	Email string `json:"email"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable refusal reason. `seat_taken`: a seated reservation lost seats to a competing claimant (TKT-173). `orphaned_seats`: the selection would strand free seats with no free neighbour (ADR-041, TKT-182).
	Code  *ErrorCode `json:"code,omitempty"`
	Error string     `json:"error"`

	// SeatIdentities With `seat_taken`: the requested seats another buyer already holds, sorted — a SUBSET of the request, forwarded verbatim from the inventory transaction that arbitrated. With `orphaned_seats`: the FREE seats the selection would strand — seats the buyer did NOT request, so the subset rule deliberately does not apply to them and a picker must keep them selectable, since adding one is the repair. Never synthesised by commerce: a refusal without a usable identity list is a 502, not a guess.
	SeatIdentities *[]string `json:"seat_identities,omitempty"`
}

// ErrorCode Machine-readable refusal reason. `seat_taken`: a seated reservation lost seats to a competing claimant (TKT-173). `orphaned_seats`: the selection would strand free seats with no free neighbour (ADR-041, TKT-182).
type ErrorCode string

// Exchange defines model for Exchange.
type Exchange struct {
	CapacityReturned   bool               `json:"capacity_returned"`
	Currency           string             `json:"currency"`
	DeltaAmount        int64              `json:"delta_amount"`
	ExchangeId         openapi_types.UUID `json:"exchange_id"`
	Quantity           int                `json:"quantity"`
	ReplacementOrderId openapi_types.UUID `json:"replacement_order_id"`
	Replay             bool               `json:"replay"`
	SourceOrderId      openapi_types.UUID `json:"source_order_id"`
	SourceTotal        int64              `json:"source_total"`
	Status             ExchangeStatus     `json:"status"`
	TargetTotal        int64              `json:"target_total"`
	TicketsExchanged   bool               `json:"tickets_exchanged"`
}

// ExchangeStatus defines model for Exchange.Status.
type ExchangeStatus string

// ExchangeCreate defines model for ExchangeCreate.
type ExchangeCreate struct {
	Actor              string             `json:"actor"`
	OrganizerId        openapi_types.UUID `json:"organizer_id"`
	Reason             string             `json:"reason"`
	TargetTicketTypeId openapi_types.UUID `json:"target_ticket_type_id"`
}

// ExchangeSwitchResult defines model for ExchangeSwitchResult.
type ExchangeSwitchResult struct {
	CapacityReturned bool               `json:"capacity_returned"`
	ExchangeId       openapi_types.UUID `json:"exchange_id"`
	TicketsExchanged bool               `json:"tickets_exchanged"`
}

// ExchangeSwitched defines model for ExchangeSwitched.
type ExchangeSwitched struct {
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// OperationalConversion defines model for OperationalConversion.
type OperationalConversion struct {
	Amount          int64              `json:"amount"`
	BuyerId         openapi_types.UUID `json:"buyer_id"`
	Currency        string             `json:"currency"`
	ExpiresAt       time.Time          `json:"expires_at"`
	HoldId          openapi_types.UUID `json:"hold_id"`
	ReservationId   openapi_types.UUID `json:"reservation_id"`
	ServerTime      time.Time          `json:"server_time"`
	SourceRemaining int                `json:"source_remaining"`
}

// OperationalConversionCreate defines model for OperationalConversionCreate.
type OperationalConversionCreate struct {
	Actor        string             `json:"actor"`
	OrganizerId  openapi_types.UUID `json:"organizer_id"`
	Quantity     int                `json:"quantity"`
	Reason       string             `json:"reason"`
	TicketTypeId openapi_types.UUID `json:"ticket_type_id"`
}

// OrderConflict defines model for OrderConflict.
type OrderConflict struct {
	Error   string              `json:"error"`
	OrderId *openapi_types.UUID `json:"order_id,omitempty"`
	Status  *string             `json:"status,omitempty"`
}

// OrderFailure defines model for OrderFailure.
type OrderFailure struct {
	OrderId              openapi_types.UUID     `json:"order_id"`
	Replay               *bool                  `json:"replay,omitempty"`
	Status               string                 `json:"status"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// OrderPending defines model for OrderPending.
type OrderPending struct {
	OrderId openapi_types.UUID `json:"order_id"`
	Status  string             `json:"status"`
}

// OrderResult defines model for OrderResult.
type OrderResult struct {
	GuestOrderRef openapi_types.UUID `json:"guest_order_ref"`
	OrderId       openapi_types.UUID `json:"order_id"`
	Status        OrderResultStatus  `json:"status"`
}

// OrderResultStatus defines model for OrderResult.Status.
type OrderResultStatus string

// OrderState defines model for OrderState.
type OrderState struct {
	OrderId openapi_types.UUID `json:"order_id"`
	Status  string             `json:"status"`
}

// Refund defines model for Refund.
type Refund struct {
	Amount           int64              `json:"amount"`
	CapacityReturned bool               `json:"capacity_returned"`
	Currency         string             `json:"currency"`
	OrderId          openapi_types.UUID `json:"order_id"`
	Quantity         int                `json:"quantity"`
	RefundId         openapi_types.UUID `json:"refund_id"`
	RefundStatus     RefundRefundStatus `json:"refund_status"`
	RefundedAmount   int64              `json:"refunded_amount"`
	RefundedQuantity int                `json:"refunded_quantity"`
	Replay           bool               `json:"replay"`
	TicketsVoided    bool               `json:"tickets_voided"`
}

// RefundRefundStatus defines model for Refund.RefundStatus.
type RefundRefundStatus string

// RefundCreate defines model for RefundCreate.
type RefundCreate struct {
	Actor       string             `json:"actor"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`
}

// Reservation defines model for Reservation.
type Reservation struct {
	Amount        int64              `json:"amount"`
	BuyerId       openapi_types.UUID `json:"buyer_id"`
	Currency      string             `json:"currency"`
	ExpiresAt     time.Time          `json:"expires_at"`
	HoldId        openapi_types.UUID `json:"hold_id"`
	ReservationId openapi_types.UUID `json:"reservation_id"`

	// Seats The seats actually claimed, sorted and de-duplicated — inventory's canonical set, never the request's array (TKT-173). Present on a seated reservation and OMITTED on a general-admission one: absence is the reservation-kind signal, and an empty array would read as a seated claim that holds nothing. It cannot be required, because every existing GA and staff-created reservation response lacks it and the response validator fails closed (ADR-028) — requiring it would turn those valid responses into runtime 500s.
	Seats      *[]string `json:"seats,omitempty"`
	ServerTime time.Time `json:"server_time"`
}

// ReservationCreate Exactly one of `quantity` (general admission) or `seat_identities` (reserved seating, TKT-173) — never both, never neither. That XOR is expressed by the property counts rather than a top-level `oneOf`: with two required properties, two optional ones and no additional properties allowed, `minProperties: 3` / `maxProperties: 3` admits exactly one of the alternatives. `oneOf` would be the obvious spelling and is avoided deliberately — the generator turns a top-level union into a json.RawMessage with As…/From… accessors instead of a usable request struct, which is a worse contract bought with a worse API. The handler enforces the same XOR independently; a caller invoking it directly must not be able to slip past the schema.
type ReservationCreate struct {
	OrganizerId openapi_types.UUID `json:"organizer_id"`

	// Quantity General admission: how many. Mutually exclusive with seat_identities.
	Quantity *int `json:"quantity,omitempty"`

	// SeatIdentities Reserved seating: exactly which seats, as stable "section/row/seat" identities read from the seat map. Mutually exclusive with quantity. The set is canonicalised (sorted, de-duplicated) by inventory, so [A,B] and [B,A] are the same request under one idempotency key — and the reservation's money follows the CLAIMED seat count, not the length of this array.
	SeatIdentities *[]string          `json:"seat_identities,omitempty"`
	TicketTypeId   openapi_types.UUID `json:"ticket_type_id"`
}

// AfterOrderId defines model for AfterOrderId.
type AfterOrderId = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizerIdQuery defines model for OrganizerIdQuery.
type OrganizerIdQuery = openapi_types.UUID

// ReportLimit defines model for ReportLimit.
type ReportLimit = int

// GetCancellationRefundReportParams defines parameters for GetCancellationRefundReport.
type GetCancellationRefundReportParams struct {
	OrganizerId  OrganizerIdQuery `form:"organizer_id" json:"organizer_id"`
	Limit        *ReportLimit     `form:"limit,omitempty" json:"limit,omitempty"`
	AfterOrderId *AfterOrderId    `form:"after_order_id,omitempty" json:"after_order_id,omitempty"`
}

// DrawDownGroupReservationParams defines parameters for DrawDownGroupReservation.
type DrawDownGroupReservationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ConvertOperationalHoldParams defines parameters for ConvertOperationalHold.
type ConvertOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ExchangeOrderParams defines parameters for ExchangeOrder.
type ExchangeOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RefundOrderParams defines parameters for RefundOrder.
type RefundOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateCancellationRefundRunParams defines parameters for CreateCancellationRefundRun.
type CreateCancellationRefundRunParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CheckoutParams defines parameters for Checkout.
type CheckoutParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateReservationParams defines parameters for CreateReservation.
type CreateReservationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ExchangeTicketsSwitchedJSONRequestBody defines body for ExchangeTicketsSwitched for application/json ContentType.
type ExchangeTicketsSwitchedJSONRequestBody = ExchangeSwitched

// DrawDownGroupReservationJSONRequestBody defines body for DrawDownGroupReservation for application/json ContentType.
type DrawDownGroupReservationJSONRequestBody = OperationalConversionCreate

// ConvertOperationalHoldJSONRequestBody defines body for ConvertOperationalHold for application/json ContentType.
type ConvertOperationalHoldJSONRequestBody = OperationalConversionCreate

// ExchangeOrderJSONRequestBody defines body for ExchangeOrder for application/json ContentType.
type ExchangeOrderJSONRequestBody = ExchangeCreate

// RefundOrderJSONRequestBody defines body for RefundOrder for application/json ContentType.
type RefundOrderJSONRequestBody = RefundCreate

// CreateCancellationRefundRunJSONRequestBody defines body for CreateCancellationRefundRun for application/json ContentType.
type CreateCancellationRefundRunJSONRequestBody = CancellationRefundCreate

// CheckoutJSONRequestBody defines body for Checkout for application/json ContentType.
type CheckoutJSONRequestBody = Checkout

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = ReservationCreate

// Getter for additional properties for OrderFailure. Returns the specified
// element and whether it was found
func (a OrderFailure) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OrderFailure
func (a *OrderFailure) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OrderFailure to handle AdditionalProperties
func (a *OrderFailure) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["order_id"]; found {
		err = json.Unmarshal(raw, &a.OrderId)
		if err != nil {
			return fmt.Errorf("error reading 'order_id': %w", err)
		}
		delete(object, "order_id")
	}

	if raw, found := object["replay"]; found {
		err = json.Unmarshal(raw, &a.Replay)
		if err != nil {
			return fmt.Errorf("error reading 'replay': %w", err)
		}
		delete(object, "replay")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OrderFailure to handle AdditionalProperties
func (a OrderFailure) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["order_id"], err = json.Marshal(a.OrderId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'order_id': %w", err)
	}

	if a.Replay != nil {
		object["replay"], err = json.Marshal(a.Replay)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'replay': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
