version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /shared/go
      - /gateway
      - /services/access
      - /services/catalog
      - /services/commerce
      - /services/inventory
      - /services/payments
      - /smoke
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /build
      - /web/scanner
      - /web/storefront
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
