// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChargeCurrency.
const (
	EUR ChargeCurrency = "EUR"
)

// Valid indicates whether the value is a known member of the ChargeCurrency enum.
func (e ChargeCurrency) Valid() bool {
	switch e {
	case EUR:
		return true
	default:
		return false
	}
}

// Charge defines model for Charge.
type Charge struct {
	Amount       int64              `json:"amount"`
	BuyerId      openapi_types.UUID `json:"buyer_id"`
	Currency     ChargeCurrency     `json:"currency"`
	OrderId      openapi_types.UUID `json:"order_id"`
	OrganizerId  openapi_types.UUID `json:"organizer_id"`
	PaymentToken string             `json:"payment_token"`
}

// ChargeCurrency defines model for Charge.Currency.
type ChargeCurrency string

// ChargeResult defines model for ChargeResult.
type ChargeResult struct {
	PaymentId openapi_types.UUID `json:"payment_id"`
	Replay    bool               `json:"replay"`
	Sequence  *int64             `json:"sequence,omitempty"`
	Status    string             `json:"status"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Fact defines model for Fact.
type Fact struct {
	Amount      int64              `json:"amount"`
	BuyerId     openapi_types.UUID `json:"buyer_id"`
	Currency    string             `json:"currency"`
	FactId      openapi_types.UUID `json:"fact_id"`
	FactType    string             `json:"fact_type"`
	OccurredAt  time.Time          `json:"occurred_at"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Payload     *map[string]string `json:"payload,omitempty"`
}

// FactResult defines model for FactResult.
type FactResult struct {
	Hash     string `json:"hash"`
	Replay   bool   `json:"replay"`
	Sequence int64  `json:"sequence"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ChargeParams defines parameters for Charge.
type ChargeParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ChargeJSONRequestBody defines body for Charge for application/json ContentType.
type ChargeJSONRequestBody = Charge

// AppendFactJSONRequestBody defines body for AppendFact for application/json ContentType.
type AppendFactJSONRequestBody = Fact
