// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ScanAcceptedDecision.
const (
	Accepted ScanAcceptedDecision = "accepted"
)

// Valid indicates whether the value is a known member of the ScanAcceptedDecision enum.
func (e ScanAcceptedDecision) Valid() bool {
	switch e {
	case Accepted:
		return true
	default:
		return false
	}
}

// Defines values for ScanRejectedDecision.
const (
	Rejected ScanRejectedDecision = "rejected"
)

// Valid indicates whether the value is a known member of the ScanRejectedDecision enum.
func (e ScanRejectedDecision) Valid() bool {
	switch e {
	case Rejected:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// LifecycleEvent defines model for LifecycleEvent.
type LifecycleEvent struct {
	Id         openapi_types.UUID `json:"id"`
	OccurredAt time.Time          `json:"occurred_at"`
	Sequence   *int64             `json:"sequence,omitempty"`
	Type       string             `json:"type"`
}

// ScanAccepted defines model for ScanAccepted.
type ScanAccepted struct {
	Decision  ScanAcceptedDecision `json:"decision"`
	ScannedAt time.Time            `json:"scanned_at"`
}

// ScanAcceptedDecision defines model for ScanAccepted.Decision.
type ScanAcceptedDecision string

// ScanRejected defines model for ScanRejected.
type ScanRejected struct {
	Decision       ScanRejectedDecision `json:"decision"`
	OriginalScanAt *time.Time           `json:"original_scan_at,omitempty"`
	Reason         string               `json:"reason"`
}

// ScanRejectedDecision defines model for ScanRejected.Decision.
type ScanRejectedDecision string

// ScanRequest defines model for ScanRequest.
type ScanRequest struct {
	QrPayload string `json:"qr_payload"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	History   []LifecycleEvent   `json:"history"`
	IssuedAt  time.Time          `json:"issued_at"`
	QrPayload string             `json:"qr_payload"`
	QrUrl     string             `json:"qr_url"`
	TicketId  openapi_types.UUID `json:"ticket_id"`
}

// TicketBundle defines model for TicketBundle.
type TicketBundle struct {
	OrderRef openapi_types.UUID `json:"order_ref"`
	Tickets  []Ticket           `json:"tickets"`
}

// Ref defines model for Ref.
type Ref = openapi_types.UUID

// ScanTicketJSONRequestBody defines body for ScanTicket for application/json ContentType.
type ScanTicketJSONRequestBody = ScanRequest
