// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvailabilityOfferingStatus.
const (
	AvailabilityOfferingStatusArchived AvailabilityOfferingStatus = "archived"
	AvailabilityOfferingStatusClosed   AvailabilityOfferingStatus = "closed"
	AvailabilityOfferingStatusOpen     AvailabilityOfferingStatus = "open"
)

// Valid indicates whether the value is a known member of the AvailabilityOfferingStatus enum.
func (e AvailabilityOfferingStatus) Valid() bool {
	switch e {
	case AvailabilityOfferingStatusArchived:
		return true
	case AvailabilityOfferingStatusClosed:
		return true
	case AvailabilityOfferingStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for CapacityAdjustmentStatus.
const (
	Applied CapacityAdjustmentStatus = "applied"
	Clamped CapacityAdjustmentStatus = "clamped"
)

// Valid indicates whether the value is a known member of the CapacityAdjustmentStatus enum.
func (e CapacityAdjustmentStatus) Valid() bool {
	switch e {
	case Applied:
		return true
	case Clamped:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ChannelWindowClosed ErrorCode = "channel_window_closed"
	OrphanedSeats       ErrorCode = "orphaned_seats"
	PinUnavailable      ErrorCode = "pin_unavailable"
	PresaleCodeInvalid  ErrorCode = "presale_code_invalid"
	SeatTaken           ErrorCode = "seat_taken"
	SeatUnavailable     ErrorCode = "seat_unavailable"
	SlotArchived        ErrorCode = "slot_archived"
	SlotClosed          ErrorCode = "slot_closed"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ChannelWindowClosed:
		return true
	case OrphanedSeats:
		return true
	case PinUnavailable:
		return true
	case PresaleCodeInvalid:
		return true
	case SeatTaken:
		return true
	case SeatUnavailable:
		return true
	case SlotArchived:
		return true
	case SlotClosed:
		return true
	default:
		return false
	}
}

// Defines values for OperationalHoldCreatePurpose.
const (
	Artist OperationalHoldCreatePurpose = "artist"
	House  OperationalHoldCreatePurpose = "house"
	Kill   OperationalHoldCreatePurpose = "kill"
	Other  OperationalHoldCreatePurpose = "other"
)

// Valid indicates whether the value is a known member of the OperationalHoldCreatePurpose enum.
func (e OperationalHoldCreatePurpose) Valid() bool {
	switch e {
	case Artist:
		return true
	case House:
		return true
	case Kill:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for SeatOccupancyOfferingStatus.
const (
	SeatOccupancyOfferingStatusArchived SeatOccupancyOfferingStatus = "archived"
	SeatOccupancyOfferingStatusClosed   SeatOccupancyOfferingStatus = "closed"
	SeatOccupancyOfferingStatusOpen     SeatOccupancyOfferingStatus = "open"
)

// Valid indicates whether the value is a known member of the SeatOccupancyOfferingStatus enum.
func (e SeatOccupancyOfferingStatus) Valid() bool {
	switch e {
	case SeatOccupancyOfferingStatusArchived:
		return true
	case SeatOccupancyOfferingStatusClosed:
		return true
	case SeatOccupancyOfferingStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for StaffAvailabilityOfferingStatus.
const (
	Archived StaffAvailabilityOfferingStatus = "archived"
	Closed   StaffAvailabilityOfferingStatus = "closed"
	Open     StaffAvailabilityOfferingStatus = "open"
)

// Valid indicates whether the value is a known member of the StaffAvailabilityOfferingStatus enum.
func (e StaffAvailabilityOfferingStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Closed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Availability defines model for Availability.
type Availability struct {
	Available int `json:"available"`
	Capacity  int `json:"capacity"`
	Confirmed int `json:"confirmed"`
	Held      int `json:"held"`

	// OfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but available is 0 unless open
	OfferingStatus AvailabilityOfferingStatus `json:"offering_status"`
	SlotId         openapi_types.UUID         `json:"slot_id"`
}

// AvailabilityOfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but available is 0 unless open
type AvailabilityOfferingStatus string

// CacheControlStatus defines model for CacheControlStatus.
type CacheControlStatus struct {
	// Enabled the state the read path itself consults, not a separate flag
	Enabled bool `json:"enabled"`

	// Entries cached entries held right now. CARDINALITY, not bytes - ADR-044 is explicit that a bounded entry count does not bound memory
	Entries int `json:"entries"`
}

// CacheControlUpdate defines model for CacheControlUpdate.
type CacheControlUpdate struct {
	// Enabled false disables the in-memory availability cache on THIS process
	Enabled bool `json:"enabled"`
}

// CapacityAdjust defines model for CapacityAdjust.
type CapacityAdjust struct {
	Actor       string             `json:"actor"`
	Capacity    int                `json:"capacity"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Reason      string             `json:"reason"`
}

// CapacityAdjustment defines model for CapacityAdjustment.
type CapacityAdjustment struct {
	// Capacity Applied ceiling after the adjustment; equals live demand while a cut is clamped
	Capacity       int                      `json:"capacity"`
	CapacityBefore int                      `json:"capacity_before"`
	ServerTime     time.Time                `json:"server_time"`
	SlotId         openapi_types.UUID       `json:"slot_id"`
	Status         CapacityAdjustmentStatus `json:"status"`

	// TargetCapacity Requested target while a clamped cut drains; absent when the adjustment applied fully
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// CapacityAdjustmentStatus defines model for CapacityAdjustment.Status.
type CapacityAdjustmentStatus string

// ChannelAllocation defines model for ChannelAllocation.
type ChannelAllocation struct {
	Cap     int    `json:"cap"`
	Channel string `json:"channel"`

	// ClosesAt End of the sales window, EXCLUSIVE. Omit for never-closes. A reversed window is refused by the schema constraint.
	ClosesAt *time.Time `json:"closes_at,omitempty"`

	// OpensAt Start of the sales window, inclusive (TKT-238). Omit for always-open.
	OpensAt *time.Time `json:"opens_at,omitempty"`

	// ReleaseAt When the unsold allocation returns to the public channel; omitted means never
	ReleaseAt *time.Time `json:"release_at,omitempty"`

	// RequiresCode Gate this allocation behind a presale unlock code (TKT-239 / ADR-055). Defaults false, so an allocation that omits it sells exactly as before. Orthogonal to the window: a window says WHEN the channel may sell, this says WHO may, and both must admit a claim.
	RequiresCode *bool `json:"requires_code,omitempty"`
}

// ChannelAllocationSet defines model for ChannelAllocationSet.
type ChannelAllocationSet struct {
	Allocations []ChannelAllocation `json:"allocations"`
	OrganizerId openapi_types.UUID  `json:"organizer_id"`
}

// ChannelAllocations defines model for ChannelAllocations.
type ChannelAllocations struct {
	Allocations []ChannelAllocation `json:"allocations"`
	SlotId      openapi_types.UUID  `json:"slot_id"`
}

// ChannelAvailability defines model for ChannelAvailability.
type ChannelAvailability struct {
	Available int    `json:"available"`
	Cap       int    `json:"cap"`
	Channel   string `json:"channel"`

	// ClosesAt End of this channel's sales window, EXCLUSIVE. Absent means never closes.
	ClosesAt  *time.Time `json:"closes_at,omitempty"`
	Confirmed int        `json:"confirmed"`
	Held      int        `json:"held"`

	// OpensAt Start of this channel's sales window (TKT-238), inclusive. Absent means always open. Half-open [opens_at, closes_at).
	OpensAt   *time.Time `json:"opens_at,omitempty"`
	ReleaseAt *time.Time `json:"release_at,omitempty"`
	Released  bool       `json:"released"`

	// WindowOpen Whether the window admits a claim right now. STAFF ONLY — the public availability read reports 0 for a closed channel and says nothing about why, because an operator needs to tell "not open yet" from "sold out" and a buyer does not.
	// Separate from `released`: a released allocation is over, a closed window is not its turn yet, and only the second fixes itself.
	WindowOpen bool `json:"window_open"`
}

// ConvertResult defines model for ConvertResult.
type ConvertResult struct {
	Hold            Hold               `json:"hold"`
	SourceId        openapi_types.UUID `json:"source_id"`
	SourceRemaining int                `json:"source_remaining"`
	SourceStatus    string             `json:"source_status"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable conflict reason; present when a dead slot, a channel outside its sales window, a missing or unusable presale code, an already-held seat, an unmapped seat, or a transient pin failure rejected the request. `channel_window_closed` is distinct from a code-less capacity refusal on purpose (TKT-238): the caller should wait for the window rather than treat the channel as sold out. `presale_code_invalid` (TKT-239) is DELIBERATELY UNIFORM across five causes — absent, unknown, wrong-channel, exhausted and out-of-window codes are indistinguishable, because a distinguishing refusal is an enumeration oracle on presale codes. Prompt for a code; do not report a sellout.
	Code  *ErrorCode `json:"code,omitempty"`
	Error string     `json:"error"`

	// SeatIdentities With `seat_taken`: the requested seats another live claim already holds, sorted (TKT-173). With `orphaned_seats`: the FREE seats this selection would strand with no free neighbour in their row (ADR-041, TKT-182) — seats the buyer did NOT request, so a caller must not assume these are a subset of what it asked for. Seats the request could have had are NOT listed — a caller re-renders exactly what it must give up. Knowable only inside the claim transaction that arbitrated: an answer computed afterwards, by re-reading occupancy say, describes a different moment and can name seats this request never lost.
	SeatIdentities *[]string `json:"seat_identities,omitempty"`
}

// ErrorCode Machine-readable conflict reason; present when a dead slot, a channel outside its sales window, a missing or unusable presale code, an already-held seat, an unmapped seat, or a transient pin failure rejected the request. `channel_window_closed` is distinct from a code-less capacity refusal on purpose (TKT-238): the caller should wait for the window rather than treat the channel as sold out. `presale_code_invalid` (TKT-239) is DELIBERATELY UNIFORM across five causes — absent, unknown, wrong-channel, exhausted and out-of-window codes are indistinguishable, because a distinguishing refusal is an enumeration oracle on presale codes. Prompt for a code; do not report a sellout.
type ErrorCode string

// GroupReservation defines model for GroupReservation.
type GroupReservation struct {
	Channel      *string            `json:"channel,omitempty"`
	Counterparty string             `json:"counterparty"`
	ExpiresAt    time.Time          `json:"expires_at"`
	HoldId       openapi_types.UUID `json:"hold_id"`
	OrganizerId  openapi_types.UUID `json:"organizer_id"`
	Quantity     int                `json:"quantity"`
	ServerTime   time.Time          `json:"server_time"`
	SlotId       openapi_types.UUID `json:"slot_id"`
	Status       string             `json:"status"`
}

// GroupReservationCreate defines model for GroupReservationCreate.
type GroupReservationCreate struct {
	Actor string `json:"actor"`

	// Channel Optional sales channel; the reservation consumes that allocation and draw-down children inherit it
	Channel      *string `json:"channel,omitempty"`
	Counterparty string  `json:"counterparty"`

	// ExpiresAt Explicit reservation expiry — must be in the future by DB time; never derived from the cart TTL
	ExpiresAt   time.Time          `json:"expires_at"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`

	// PresaleCode Presale unlock code, when the channel is gated (TKT-239). Redeemed ONCE, by this placement; draw-down children deliberately do not cite it, so drawing down never consumes another redemption.
	PresaleCode *string            `json:"presale_code,omitempty"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`
	SlotId      openapi_types.UUID `json:"slot_id"`
}

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	Action         string              `json:"action"`
	Actor          string              `json:"actor"`
	OccurredAt     time.Time           `json:"occurred_at"`
	Quantity       int                 `json:"quantity"`
	QuantityAfter  int                 `json:"quantity_after"`
	Reason         string              `json:"reason"`
	RelatedClaimId *openapi_types.UUID `json:"related_claim_id,omitempty"`
	StatusAfter    string              `json:"status_after"`

	// TargetCapacity Capacity-adjustment records only (TKT-76): the requested target while a clamped cut drains
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// Hold defines model for Hold.
type Hold struct {
	Channel      *string             `json:"channel,omitempty"`
	Currency     *string             `json:"currency,omitempty"`
	ExpiresAt    time.Time           `json:"expires_at"`
	HoldId       openapi_types.UUID  `json:"hold_id"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	ServerTime   time.Time           `json:"server_time"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	Status       string              `json:"status"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// HoldCreate defines model for HoldCreate.
type HoldCreate struct {
	// Channel Opaque sales channel code; omitted means the default/public channel
	Channel     *string            `json:"channel,omitempty"`
	Currency    *string            `json:"currency,omitempty"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`

	// PresaleCode Presale unlock code for a gated channel (TKT-239). EXACT and case-sensitive like the channel code — nothing trims or folds it. Required only when the channel's allocation sets requires_code; ignored (and not recorded) otherwise. A missing or unusable code is refused with the uniform `presale_code_invalid`.
	PresaleCode  *string             `json:"presale_code,omitempty"`
	Quantity     int                 `json:"quantity"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// HoldSeating defines model for HoldSeating.
type HoldSeating struct {
	HoldId openapi_types.UUID `json:"hold_id"`
	Seated bool               `json:"seated"`
}

// OperationalConvert defines model for OperationalConvert.
type OperationalConvert struct {
	Actor       string             `json:"actor"`
	Currency    string             `json:"currency"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`

	// SlotId The slot the caller priced against; verified against the hold's pool before any write
	SlotId       openapi_types.UUID `json:"slot_id"`
	TicketTypeId openapi_types.UUID `json:"ticket_type_id"`
	UnitAmount   int64              `json:"unit_amount"`
}

// OperationalHold defines model for OperationalHold.
type OperationalHold struct {
	HoldId      openapi_types.UUID `json:"hold_id"`
	Label       *string            `json:"label,omitempty"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Purpose     *string            `json:"purpose,omitempty"`
	Quantity    int                `json:"quantity"`
	ServerTime  time.Time          `json:"server_time"`
	SlotId      openapi_types.UUID `json:"slot_id"`
	Status      string             `json:"status"`
}

// OperationalHoldCreate defines model for OperationalHoldCreate.
type OperationalHoldCreate struct {
	Actor       string                       `json:"actor"`
	Label       string                       `json:"label"`
	OrganizerId openapi_types.UUID           `json:"organizer_id"`
	Purpose     OperationalHoldCreatePurpose `json:"purpose"`
	Quantity    int                          `json:"quantity"`
	Reason      string                       `json:"reason"`
	SlotId      openapi_types.UUID           `json:"slot_id"`
}

// OperationalHoldCreatePurpose defines model for OperationalHoldCreate.Purpose.
type OperationalHoldCreatePurpose string

// OperationalRelease defines model for OperationalRelease.
type OperationalRelease struct {
	Actor       string             `json:"actor"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`
}

// RefundCapacityReturn defines model for RefundCapacityReturn.
type RefundCapacityReturn struct {
	HoldId             openapi_types.UUID `json:"hold_id"`
	Quantity           int                `json:"quantity"`
	Replay             bool               `json:"replay"`
	UnreturnedQuantity int                `json:"unreturned_quantity"`
}

// RefundCapacityReturnCreate defines model for RefundCapacityReturnCreate.
type RefundCapacityReturnCreate struct {
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	RefundId    openapi_types.UUID `json:"refund_id"`
}

// SeatHold defines model for SeatHold.
type SeatHold struct {
	Channel      *string             `json:"channel,omitempty"`
	Currency     *string             `json:"currency,omitempty"`
	ExpiresAt    time.Time           `json:"expires_at"`
	HoldId       openapi_types.UUID  `json:"hold_id"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	Seats        []string            `json:"seats"`
	ServerTime   time.Time           `json:"server_time"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	Status       string              `json:"status"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// SeatHoldCreate defines model for SeatHoldCreate.
type SeatHoldCreate struct {
	Currency       string             `json:"currency"`
	OrganizerId    openapi_types.UUID `json:"organizer_id"`
	SeatIdentities []string           `json:"seat_identities"`
	SlotId         openapi_types.UUID `json:"slot_id"`
	TicketTypeId   openapi_types.UUID `json:"ticket_type_id"`
	UnitAmount     int64              `json:"unit_amount"`
}

// SeatOccupancy defines model for SeatOccupancy.
type SeatOccupancy struct {
	// OfferingStatus Catalog offer state mirrored by inventory (TKT-75). The seat list stays factual whatever this says — it is how a caller tells "these seats are free" from "nothing on this slot is claimable at all"
	OfferingStatus SeatOccupancyOfferingStatus `json:"offering_status"`

	// RemainingCapacity The pool's remaining aggregate headroom under exactly the test the seated claim path applies (target_capacity when a cut is pending, else capacity, minus confirmed and live held), and 0 on a slot that is not open. A CEILING, not a seat count — inventory does not hold the seat universe, that is the seat map in catalog, and a seated pool is provisioned from the venue's GA snapshot. So it reads high when a small map sits in a large venue, and 0 when a capacity cut has drained a pool whose seats are free. Deliberately NOT the availability read's `available`, which additionally subtracts unsold channel reservations that the seated claim path never consults. A picker must gate on BOTH this and unavailable_seat_identities; neither is sufficient alone.
	RemainingCapacity int `json:"remaining_capacity"`

	// SeatMapId The published seat-map version this slot is seated against, as inventory holds it. Catalog publishes its own view on the performance; the two agreeing is what makes projection skew detectable rather than hidden.
	SeatMapId openapi_types.UUID `json:"seat_map_id"`
	SlotId    openapi_types.UUID `json:"slot_id"`

	// UnavailableSeatIdentities Sorted, and [] rather than null on an empty seated pool — which is a different answer from 404 on an unknown slot
	UnavailableSeatIdentities []string `json:"unavailable_seat_identities"`
}

// SeatOccupancyOfferingStatus Catalog offer state mirrored by inventory (TKT-75). The seat list stays factual whatever this says — it is how a caller tells "these seats are free" from "nothing on this slot is claimable at all"
type SeatOccupancyOfferingStatus string

// StaffAvailability defines model for StaffAvailability.
type StaffAvailability struct {
	Available int `json:"available"`
	BuyerHeld int `json:"buyer_held"`

	// Capacity Effective capacity: the clamp floor while a cut drains (TKT-76)
	Capacity  int                   `json:"capacity"`
	Channels  []ChannelAvailability `json:"channels"`
	Confirmed int                   `json:"confirmed"`

	// OfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but claimable availability is 0 unless open
	OfferingStatus  StaffAvailabilityOfferingStatus `json:"offering_status"`
	OperationalHeld int                             `json:"operational_held"`
	PublicAvailable int                             `json:"public_available"`

	// ReservationHeld Live group/agency reservation quantity (TKT-79)
	ReservationHeld int                `json:"reservation_held"`
	SlotId          openapi_types.UUID `json:"slot_id"`

	// TargetCapacity Requested target while a clamped cut drains; absent otherwise
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// StaffAvailabilityOfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but claimable availability is 0 unless open
type StaffAvailabilityOfferingStatus string

// Id defines model for Id.
type Id = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizerId defines model for OrganizerId.
type OrganizerId = openapi_types.UUID

// CreateHoldParams defines parameters for CreateHold.
type CreateHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateSeatHoldParams defines parameters for CreateSeatHold.
type CreateSeatHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PlaceGroupReservationParams defines parameters for PlaceGroupReservation.
type PlaceGroupReservationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DrawDownGroupReservationParams defines parameters for DrawDownGroupReservation.
type DrawDownGroupReservationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetGroupReservationHistoryParams defines parameters for GetGroupReservationHistory.
type GetGroupReservationHistoryParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ConfirmHoldParams defines parameters for ConfirmHold.
type ConfirmHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// FinalizeHoldParams defines parameters for FinalizeHold.
type FinalizeHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ReleaseHoldParams defines parameters for ReleaseHold.
type ReleaseHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// GetHoldSeatingParams defines parameters for GetHoldSeating.
type GetHoldSeatingParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// PlaceOperationalHoldParams defines parameters for PlaceOperationalHold.
type PlaceOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ConvertOperationalHoldParams defines parameters for ConvertOperationalHold.
type ConvertOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetOperationalHoldHistoryParams defines parameters for GetOperationalHoldHistory.
type GetOperationalHoldHistoryParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ReleaseOperationalHoldParams defines parameters for ReleaseOperationalHold.
type ReleaseOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetStaffAvailabilityParams defines parameters for GetStaffAvailability.
type GetStaffAvailabilityParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// GetCapacityAdjustmentsParams defines parameters for GetCapacityAdjustments.
type GetCapacityAdjustmentsParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// AdjustCapacityParams defines parameters for AdjustCapacity.
type AdjustCapacityParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetAvailabilityParams defines parameters for GetAvailability.
type GetAvailabilityParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`

	// Channel Scope `available` to this sales channel; omitted means the default/public channel
	Channel *string `form:"channel,omitempty" json:"channel,omitempty"`
}

// GetSeatOccupancyParams defines parameters for GetSeatOccupancy.
type GetSeatOccupancyParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// CreateHoldJSONRequestBody defines body for CreateHold for application/json ContentType.
type CreateHoldJSONRequestBody = HoldCreate

// CreateSeatHoldJSONRequestBody defines body for CreateSeatHold for application/json ContentType.
type CreateSeatHoldJSONRequestBody = SeatHoldCreate

// PutCacheControlJSONRequestBody defines body for PutCacheControl for application/json ContentType.
type PutCacheControlJSONRequestBody = CacheControlUpdate

// PlaceGroupReservationJSONRequestBody defines body for PlaceGroupReservation for application/json ContentType.
type PlaceGroupReservationJSONRequestBody = GroupReservationCreate

// DrawDownGroupReservationJSONRequestBody defines body for DrawDownGroupReservation for application/json ContentType.
type DrawDownGroupReservationJSONRequestBody = OperationalConvert

// ReturnRefundedCapacityJSONRequestBody defines body for ReturnRefundedCapacity for application/json ContentType.
type ReturnRefundedCapacityJSONRequestBody = RefundCapacityReturnCreate

// PlaceOperationalHoldJSONRequestBody defines body for PlaceOperationalHold for application/json ContentType.
type PlaceOperationalHoldJSONRequestBody = OperationalHoldCreate

// ConvertOperationalHoldJSONRequestBody defines body for ConvertOperationalHold for application/json ContentType.
type ConvertOperationalHoldJSONRequestBody = OperationalConvert

// ReleaseOperationalHoldJSONRequestBody defines body for ReleaseOperationalHold for application/json ContentType.
type ReleaseOperationalHoldJSONRequestBody = OperationalRelease

// AdjustCapacityJSONRequestBody defines body for AdjustCapacity for application/json ContentType.
type AdjustCapacityJSONRequestBody = CapacityAdjust

// ReplaceChannelAllocationsJSONRequestBody defines body for ReplaceChannelAllocations for application/json ContentType.
type ReplaceChannelAllocationsJSONRequestBody = ChannelAllocationSet
