// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Availability defines model for Availability.
type Availability struct {
	Available int                `json:"available"`
	Capacity  int                `json:"capacity"`
	Confirmed int                `json:"confirmed"`
	Held      int                `json:"held"`
	SlotId    openapi_types.UUID `json:"slot_id"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Hold defines model for Hold.
type Hold struct {
	Currency     *string             `json:"currency,omitempty"`
	ExpiresAt    time.Time           `json:"expires_at"`
	HoldId       openapi_types.UUID  `json:"hold_id"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	ServerTime   time.Time           `json:"server_time"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	Status       string              `json:"status"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// HoldCreate defines model for HoldCreate.
type HoldCreate struct {
	Currency     *string             `json:"currency,omitempty"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// Id defines model for Id.
type Id = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizerId defines model for OrganizerId.
type OrganizerId = openapi_types.UUID

// CreateHoldParams defines parameters for CreateHold.
type CreateHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ConfirmHoldParams defines parameters for ConfirmHold.
type ConfirmHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// FinalizeHoldParams defines parameters for FinalizeHold.
type FinalizeHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ReleaseHoldParams defines parameters for ReleaseHold.
type ReleaseHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// GetAvailabilityParams defines parameters for GetAvailability.
type GetAvailabilityParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// CreateHoldJSONRequestBody defines body for CreateHold for application/json ContentType.
type CreateHoldJSONRequestBody = HoldCreate
