// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AvailabilityOfferingStatus.
const (
	AvailabilityOfferingStatusArchived AvailabilityOfferingStatus = "archived"
	AvailabilityOfferingStatusClosed   AvailabilityOfferingStatus = "closed"
	AvailabilityOfferingStatusOpen     AvailabilityOfferingStatus = "open"
)

// Valid indicates whether the value is a known member of the AvailabilityOfferingStatus enum.
func (e AvailabilityOfferingStatus) Valid() bool {
	switch e {
	case AvailabilityOfferingStatusArchived:
		return true
	case AvailabilityOfferingStatusClosed:
		return true
	case AvailabilityOfferingStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for CapacityAdjustmentStatus.
const (
	Applied CapacityAdjustmentStatus = "applied"
	Clamped CapacityAdjustmentStatus = "clamped"
)

// Valid indicates whether the value is a known member of the CapacityAdjustmentStatus enum.
func (e CapacityAdjustmentStatus) Valid() bool {
	switch e {
	case Applied:
		return true
	case Clamped:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	SlotArchived ErrorCode = "slot_archived"
	SlotClosed   ErrorCode = "slot_closed"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case SlotArchived:
		return true
	case SlotClosed:
		return true
	default:
		return false
	}
}

// Defines values for OperationalHoldCreatePurpose.
const (
	Artist OperationalHoldCreatePurpose = "artist"
	House  OperationalHoldCreatePurpose = "house"
	Kill   OperationalHoldCreatePurpose = "kill"
	Other  OperationalHoldCreatePurpose = "other"
)

// Valid indicates whether the value is a known member of the OperationalHoldCreatePurpose enum.
func (e OperationalHoldCreatePurpose) Valid() bool {
	switch e {
	case Artist:
		return true
	case House:
		return true
	case Kill:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for StaffAvailabilityOfferingStatus.
const (
	StaffAvailabilityOfferingStatusArchived StaffAvailabilityOfferingStatus = "archived"
	StaffAvailabilityOfferingStatusClosed   StaffAvailabilityOfferingStatus = "closed"
	StaffAvailabilityOfferingStatusOpen     StaffAvailabilityOfferingStatus = "open"
)

// Valid indicates whether the value is a known member of the StaffAvailabilityOfferingStatus enum.
func (e StaffAvailabilityOfferingStatus) Valid() bool {
	switch e {
	case StaffAvailabilityOfferingStatusArchived:
		return true
	case StaffAvailabilityOfferingStatusClosed:
		return true
	case StaffAvailabilityOfferingStatusOpen:
		return true
	default:
		return false
	}
}

// Availability defines model for Availability.
type Availability struct {
	Available int `json:"available"`
	Capacity  int `json:"capacity"`
	Confirmed int `json:"confirmed"`
	Held      int `json:"held"`

	// OfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but available is 0 unless open
	OfferingStatus AvailabilityOfferingStatus `json:"offering_status"`
	SlotId         openapi_types.UUID         `json:"slot_id"`
}

// AvailabilityOfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but available is 0 unless open
type AvailabilityOfferingStatus string

// CapacityAdjust defines model for CapacityAdjust.
type CapacityAdjust struct {
	Actor       string             `json:"actor"`
	Capacity    int                `json:"capacity"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Reason      string             `json:"reason"`
}

// CapacityAdjustment defines model for CapacityAdjustment.
type CapacityAdjustment struct {
	// Capacity Applied ceiling after the adjustment; equals live demand while a cut is clamped
	Capacity       int                      `json:"capacity"`
	CapacityBefore int                      `json:"capacity_before"`
	ServerTime     time.Time                `json:"server_time"`
	SlotId         openapi_types.UUID       `json:"slot_id"`
	Status         CapacityAdjustmentStatus `json:"status"`

	// TargetCapacity Requested target while a clamped cut drains; absent when the adjustment applied fully
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// CapacityAdjustmentStatus defines model for CapacityAdjustment.Status.
type CapacityAdjustmentStatus string

// ChannelAllocation defines model for ChannelAllocation.
type ChannelAllocation struct {
	Cap     int    `json:"cap"`
	Channel string `json:"channel"`

	// ReleaseAt When the unsold allocation returns to the public channel; omitted means never
	ReleaseAt *time.Time `json:"release_at,omitempty"`
}

// ChannelAllocationSet defines model for ChannelAllocationSet.
type ChannelAllocationSet struct {
	Allocations []ChannelAllocation `json:"allocations"`
	OrganizerId openapi_types.UUID  `json:"organizer_id"`
}

// ChannelAllocations defines model for ChannelAllocations.
type ChannelAllocations struct {
	Allocations []ChannelAllocation `json:"allocations"`
	SlotId      openapi_types.UUID  `json:"slot_id"`
}

// ChannelAvailability defines model for ChannelAvailability.
type ChannelAvailability struct {
	Available int        `json:"available"`
	Cap       int        `json:"cap"`
	Channel   string     `json:"channel"`
	Confirmed int        `json:"confirmed"`
	Held      int        `json:"held"`
	ReleaseAt *time.Time `json:"release_at,omitempty"`
	Released  bool       `json:"released"`
}

// ConvertResult defines model for ConvertResult.
type ConvertResult struct {
	Hold            Hold               `json:"hold"`
	SourceId        openapi_types.UUID `json:"source_id"`
	SourceRemaining int                `json:"source_remaining"`
	SourceStatus    string             `json:"source_status"`
}

// Error defines model for Error.
type Error struct {
	// Code Machine-readable conflict reason; present when a dead slot (not contention) rejected the request
	Code  *ErrorCode `json:"code,omitempty"`
	Error string     `json:"error"`
}

// ErrorCode Machine-readable conflict reason; present when a dead slot (not contention) rejected the request
type ErrorCode string

// HistoryEntry defines model for HistoryEntry.
type HistoryEntry struct {
	Action         string              `json:"action"`
	Actor          string              `json:"actor"`
	OccurredAt     time.Time           `json:"occurred_at"`
	Quantity       int                 `json:"quantity"`
	QuantityAfter  int                 `json:"quantity_after"`
	Reason         string              `json:"reason"`
	RelatedClaimId *openapi_types.UUID `json:"related_claim_id,omitempty"`
	StatusAfter    string              `json:"status_after"`

	// TargetCapacity Capacity-adjustment records only (TKT-76): the requested target while a clamped cut drains
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// Hold defines model for Hold.
type Hold struct {
	Channel      *string             `json:"channel,omitempty"`
	Currency     *string             `json:"currency,omitempty"`
	ExpiresAt    time.Time           `json:"expires_at"`
	HoldId       openapi_types.UUID  `json:"hold_id"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	ServerTime   time.Time           `json:"server_time"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	Status       string              `json:"status"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// HoldCreate defines model for HoldCreate.
type HoldCreate struct {
	// Channel Opaque sales channel code; omitted means the default/public channel
	Channel      *string             `json:"channel,omitempty"`
	Currency     *string             `json:"currency,omitempty"`
	OrganizerId  openapi_types.UUID  `json:"organizer_id"`
	Quantity     int                 `json:"quantity"`
	SlotId       openapi_types.UUID  `json:"slot_id"`
	TicketTypeId *openapi_types.UUID `json:"ticket_type_id,omitempty"`
	UnitAmount   *int64              `json:"unit_amount,omitempty"`
}

// OperationalConvert defines model for OperationalConvert.
type OperationalConvert struct {
	Actor       string             `json:"actor"`
	Currency    string             `json:"currency"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`

	// SlotId The slot the caller priced against; verified against the hold's pool before any write
	SlotId       openapi_types.UUID `json:"slot_id"`
	TicketTypeId openapi_types.UUID `json:"ticket_type_id"`
	UnitAmount   int64              `json:"unit_amount"`
}

// OperationalHold defines model for OperationalHold.
type OperationalHold struct {
	HoldId      openapi_types.UUID `json:"hold_id"`
	Label       *string            `json:"label,omitempty"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Purpose     *string            `json:"purpose,omitempty"`
	Quantity    int                `json:"quantity"`
	ServerTime  time.Time          `json:"server_time"`
	SlotId      openapi_types.UUID `json:"slot_id"`
	Status      string             `json:"status"`
}

// OperationalHoldCreate defines model for OperationalHoldCreate.
type OperationalHoldCreate struct {
	Actor       string                       `json:"actor"`
	Label       string                       `json:"label"`
	OrganizerId openapi_types.UUID           `json:"organizer_id"`
	Purpose     OperationalHoldCreatePurpose `json:"purpose"`
	Quantity    int                          `json:"quantity"`
	Reason      string                       `json:"reason"`
	SlotId      openapi_types.UUID           `json:"slot_id"`
}

// OperationalHoldCreatePurpose defines model for OperationalHoldCreate.Purpose.
type OperationalHoldCreatePurpose string

// OperationalRelease defines model for OperationalRelease.
type OperationalRelease struct {
	Actor       string             `json:"actor"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
	Quantity    int                `json:"quantity"`
	Reason      string             `json:"reason"`
}

// StaffAvailability defines model for StaffAvailability.
type StaffAvailability struct {
	Available int `json:"available"`
	BuyerHeld int `json:"buyer_held"`

	// Capacity Effective capacity: the clamp floor while a cut drains (TKT-76)
	Capacity  int                   `json:"capacity"`
	Channels  []ChannelAvailability `json:"channels"`
	Confirmed int                   `json:"confirmed"`

	// OfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but claimable availability is 0 unless open
	OfferingStatus  StaffAvailabilityOfferingStatus `json:"offering_status"`
	OperationalHeld int                             `json:"operational_held"`
	PublicAvailable int                             `json:"public_available"`
	SlotId          openapi_types.UUID              `json:"slot_id"`

	// TargetCapacity Requested target while a clamped cut drains; absent otherwise
	TargetCapacity *int `json:"target_capacity,omitempty"`
}

// StaffAvailabilityOfferingStatus Catalog offer state mirrored by inventory (TKT-75): counters stay factual, but claimable availability is 0 unless open
type StaffAvailabilityOfferingStatus string

// Id defines model for Id.
type Id = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizerId defines model for OrganizerId.
type OrganizerId = openapi_types.UUID

// CreateHoldParams defines parameters for CreateHold.
type CreateHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ConfirmHoldParams defines parameters for ConfirmHold.
type ConfirmHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// FinalizeHoldParams defines parameters for FinalizeHold.
type FinalizeHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ReleaseHoldParams defines parameters for ReleaseHold.
type ReleaseHoldParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// PlaceOperationalHoldParams defines parameters for PlaceOperationalHold.
type PlaceOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ConvertOperationalHoldParams defines parameters for ConvertOperationalHold.
type ConvertOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetOperationalHoldHistoryParams defines parameters for GetOperationalHoldHistory.
type GetOperationalHoldHistoryParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// ReleaseOperationalHoldParams defines parameters for ReleaseOperationalHold.
type ReleaseOperationalHoldParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetStaffAvailabilityParams defines parameters for GetStaffAvailability.
type GetStaffAvailabilityParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// GetCapacityAdjustmentsParams defines parameters for GetCapacityAdjustments.
type GetCapacityAdjustmentsParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`
}

// AdjustCapacityParams defines parameters for AdjustCapacity.
type AdjustCapacityParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetAvailabilityParams defines parameters for GetAvailability.
type GetAvailabilityParams struct {
	OrganizerId OrganizerId `form:"organizer_id" json:"organizer_id"`

	// Channel Scope `available` to this sales channel; omitted means the default/public channel
	Channel *string `form:"channel,omitempty" json:"channel,omitempty"`
}

// CreateHoldJSONRequestBody defines body for CreateHold for application/json ContentType.
type CreateHoldJSONRequestBody = HoldCreate

// PlaceOperationalHoldJSONRequestBody defines body for PlaceOperationalHold for application/json ContentType.
type PlaceOperationalHoldJSONRequestBody = OperationalHoldCreate

// ConvertOperationalHoldJSONRequestBody defines body for ConvertOperationalHold for application/json ContentType.
type ConvertOperationalHoldJSONRequestBody = OperationalConvert

// ReleaseOperationalHoldJSONRequestBody defines body for ReleaseOperationalHold for application/json ContentType.
type ReleaseOperationalHoldJSONRequestBody = OperationalRelease

// AdjustCapacityJSONRequestBody defines body for AdjustCapacity for application/json ContentType.
type AdjustCapacityJSONRequestBody = CapacityAdjust

// ReplaceChannelAllocationsJSONRequestBody defines body for ReplaceChannelAllocations for application/json ContentType.
type ReplaceChannelAllocationsJSONRequestBody = ChannelAllocationSet
