// Back-office credential separation, checked ONCE at startup (TKT-194).
//
// Plain .mjs at the package root, outside src/, so BOTH entrypoints can share
// one copy of the rule: start.mjs runs it before the server listens, and
// middleware.ts runs it again per module load as defence in depth. A security
// rule written twice is a security rule that will disagree with itself.
//
// It does not throw on import — the callers decide what to do — so its own test
// can import it.
//
// That distinction is the whole finding (ai-review pass 1). An earlier version
// compared the two credentials inside `refundOrder`, which meant a deployment
// with both set to the same value started normally, passed its healthcheck, and
// served every page: the internet-facing SSR process held one bearer value
// opening BOTH catalog writes and commerce refunds, and nothing anywhere
// noticed. An attacker who compromised the process would use that value
// directly and never call the helper that was supposed to object.
//
// The Go services cannot catch this pair. Catalog compares its credential
// against INTERNAL_SERVICE_TOKEN and commerce compares its own; neither is ever
// given the other's, by design. The back office is the only process that holds
// both, so it is the only one that can compare them.

// The credentials this process holds, each with what it opens — used both for the
// "is it set" message and for the pairwise comparison below. TKT-244 added the third
// (inventory, ADR-057); a list rather than three hand-written comparisons because with
// three values there are three pairs, and the pair a hand-written check forgets is
// exactly the one that collapses silently.
const CREDENTIALS = [
  ['CATALOG_STAFF_WRITE_TOKEN', 'the back office cannot write to catalog'],
  ['COMMERCE_STAFF_WRITE_TOKEN', 'the back office cannot refund'],
  ['INVENTORY_STAFF_WRITE_TOKEN', 'the back office cannot edit channel allocations'],
];

/** Throws if any of the back office's staff credentials is missing, or any two match. */
export function assertCredentialSeparation(env = process.env) {
  for (const [name, consequence] of CREDENTIALS) {
    if (!env[name]) {
      throw new Error(
        `${name} is not set: ${consequence}. ` +
          'It is generated by `make up` and supplied by compose.',
      );
    }
  }
  // Every pair, so no collapse can hide behind another pair being distinct.
  for (let i = 0; i < CREDENTIALS.length; i++) {
    for (let j = i + 1; j < CREDENTIALS.length; j++) {
      const [a] = CREDENTIALS[i];
      const [b] = CREDENTIALS[j];
      if (env[a] === env[b]) {
        // Neither value is echoed.
        throw new Error(
          `${a} must not equal ${b}: they exist to have different blast radii — ` +
            'one authors catalog content, one moves money, one configures inventory ' +
            'capacity — and identical values collapse that boundary while looking configured.',
        );
      }
    }
  }
}
