// Back-office credential separation, checked ONCE at startup (TKT-194).
//
// Plain .mjs at the package root, outside src/, so BOTH entrypoints can share
// one copy of the rule: start.mjs runs it before the server listens, and
// middleware.ts runs it again per module load as defence in depth. A security
// rule written twice is a security rule that will disagree with itself.
//
// It does not throw on import — the callers decide what to do — so its own test
// can import it.
//
// That distinction is the whole finding (ai-review pass 1). An earlier version
// compared the two credentials inside `refundOrder`, which meant a deployment
// with both set to the same value started normally, passed its healthcheck, and
// served every page: the internet-facing SSR process held one bearer value
// opening BOTH catalog writes and commerce refunds, and nothing anywhere
// noticed. An attacker who compromised the process would use that value
// directly and never call the helper that was supposed to object.
//
// The Go services cannot catch this pair. Catalog compares its credential
// against INTERNAL_SERVICE_TOKEN and commerce compares its own; neither is ever
// given the other's, by design. The back office is the only process that holds
// both, so it is the only one that can compare them.

/** Throws if the back office's two staff credentials are missing or identical. */
export function assertCredentialSeparation(env = process.env) {
  const catalog = env.CATALOG_STAFF_WRITE_TOKEN;
  const commerce = env.COMMERCE_STAFF_WRITE_TOKEN;
  if (!catalog) {
    throw new Error(
      'CATALOG_STAFF_WRITE_TOKEN is not set: the back office cannot write to catalog. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  if (!commerce) {
    throw new Error(
      'COMMERCE_STAFF_WRITE_TOKEN is not set: the back office cannot refund. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  if (catalog === commerce) {
    // Neither value is echoed.
    throw new Error(
      'CATALOG_STAFF_WRITE_TOKEN must not equal COMMERCE_STAFF_WRITE_TOKEN: they exist to have ' +
        'different blast radii — one authors catalog content, the other moves money — and ' +
        'identical values collapse that boundary while looking configured.',
    );
  }
}
