// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClosureStatus.
const (
	Closed ClosureStatus = "closed"
	Open   ClosureStatus = "open"
)

// Valid indicates whether the value is a known member of the ClosureStatus enum.
func (e ClosureStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for PerformanceStatus.
const (
	Archived  PerformanceStatus = "archived"
	Draft     PerformanceStatus = "draft"
	Published PerformanceStatus = "published"
)

// Valid indicates whether the value is a known member of the PerformanceStatus enum.
func (e PerformanceStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for ReEntryPolicyMode.
const (
	CountLimited ReEntryPolicyMode = "count_limited"
	Multi        ReEntryPolicyMode = "multi"
	Single       ReEntryPolicyMode = "single"
)

// Valid indicates whether the value is a known member of the ReEntryPolicyMode enum.
func (e ReEntryPolicyMode) Valid() bool {
	switch e {
	case CountLimited:
		return true
	case Multi:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for SlotKind.
const (
	SlotKindFestivalDay  SlotKind = "festival_day"
	SlotKindOperatingDay SlotKind = "operating_day"
	SlotKindPerformance  SlotKind = "performance"
)

// Valid indicates whether the value is a known member of the SlotKind enum.
func (e SlotKind) Valid() bool {
	switch e {
	case SlotKindFestivalDay:
		return true
	case SlotKindOperatingDay:
		return true
	case SlotKindPerformance:
		return true
	default:
		return false
	}
}

// Closure Weather-closure state (spike §Case 3), orthogonal to the draft/published/archived lifecycle. A closed slot is still published.
type Closure struct {
	ClosedAt *time.Time    `json:"closed_at,omitempty"`
	Reason   *string       `json:"reason,omitempty"`
	Status   ClosureStatus `json:"status"`
}

// ClosureStatus defines model for Closure.Status.
type ClosureStatus string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt time.Time `json:"created_at"`

	// Description Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Description *LocalizedString   `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString    `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// EventCreate defines model for EventCreate.
type EventCreate struct {
	// Description Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Description *LocalizedString `json:"description,omitempty"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString    `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// LocalizedString Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
type LocalizedString map[string]string

// Money Integer minor units + ISO-4217 code (ADR-001); no floats, ever
type Money struct {
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

// Performance defines model for Performance.
type Performance struct {
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	ClosesAt   *string    `json:"closes_at,omitempty"`

	// Closure Weather-closure state (spike §Case 3), orthogonal to the draft/published/archived lifecycle. A closed slot is still published.
	Closure   Closure            `json:"closure"`
	CreatedAt time.Time          `json:"created_at"`
	EventId   openapi_types.UUID `json:"event_id"`
	Id        openapi_types.UUID `json:"id"`

	// Kind The dated-slot kind (ADR-005 amendment / US-009). 'performance' carries starts_at; 'festival_day'/'operating_day' carry the operating window.
	Kind          SlotKind            `json:"kind"`
	OpensAt       *string             `json:"opens_at,omitempty"`
	OperatingDate *openapi_types.Date `json:"operating_date,omitempty"`
	OrganizerId   openapi_types.UUID  `json:"organizer_id"`
	PublishedAt   *time.Time          `json:"published_at,omitempty"`

	// ReEntry How many admissions one entitlement grants on the slot (spike §Case 1). 'single' is the performance case; 'count_limited' requires max_entries.
	ReEntry ReEntryPolicy `json:"re_entry"`

	// StartsAt Present for kind 'performance'; absent for day kinds
	StartsAt *time.Time         `json:"starts_at,omitempty"`
	Status   PerformanceStatus  `json:"status"`
	Timezone string             `json:"timezone"`
	VenueId  openapi_types.UUID `json:"venue_id"`
}

// PerformanceStatus defines model for Performance.Status.
type PerformanceStatus string

// PerformanceCreate Creates a dated slot in draft. kind defaults to 'performance' (which requires starts_at); 'festival_day'/'operating_day' require the operating window (operating_date + opens_at + closes_at). re_entry defaults to single-entry.
type PerformanceCreate struct {
	// ClosesAt Local closing time-of-day (HH:MM); < opens_at spans midnight
	ClosesAt *string            `json:"closes_at,omitempty"`
	EventId  openapi_types.UUID `json:"event_id"`

	// Kind The dated-slot kind (ADR-005 amendment / US-009). 'performance' carries starts_at; 'festival_day'/'operating_day' carry the operating window.
	Kind *SlotKind `json:"kind,omitempty"`

	// OpensAt Local opening time-of-day (HH:MM) for day kinds
	OpensAt *string `json:"opens_at,omitempty"`

	// OperatingDate Local operating date for day kinds
	OperatingDate *openapi_types.Date `json:"operating_date,omitempty"`
	OrganizerId   openapi_types.UUID  `json:"organizer_id"`

	// ReEntry How many admissions one entitlement grants on the slot (spike §Case 1). 'single' is the performance case; 'count_limited' requires max_entries.
	ReEntry *ReEntryPolicy `json:"re_entry,omitempty"`

	// StartsAt Instant for kind 'performance'; omit for day kinds
	StartsAt *time.Time `json:"starts_at,omitempty"`

	// Timezone IANA zone name, e.g. Europe/Paris
	Timezone string             `json:"timezone"`
	VenueId  openapi_types.UUID `json:"venue_id"`
}

// PublicEventDetail defines model for PublicEventDetail.
type PublicEventDetail struct {
	Description  *string                   `json:"description,omitempty"`
	Id           openapi_types.UUID        `json:"id"`
	Name         string                    `json:"name"`
	OrganizerId  openapi_types.UUID        `json:"organizer_id"`
	Performances []PublicPerformanceDetail `json:"performances"`
	Series       []PublicSeriesContext     `json:"series"`
}

// PublicEventList defines model for PublicEventList.
type PublicEventList struct {
	Events []PublicEventSummary `json:"events"`
}

// PublicEventSummary defines model for PublicEventSummary.
type PublicEventSummary struct {
	Description  *string                    `json:"description,omitempty"`
	Id           openapi_types.UUID         `json:"id"`
	Name         string                     `json:"name"`
	Performances []PublicPerformanceSummary `json:"performances"`
}

// PublicPerformanceDetail defines model for PublicPerformanceDetail.
type PublicPerformanceDetail struct {
	Id          openapi_types.UUID `json:"id"`
	StartsAt    time.Time          `json:"starts_at"`
	TicketTypes []PublicTicketType `json:"ticket_types"`
	Timezone    string             `json:"timezone"`
	Venue       PublicVenue        `json:"venue"`
}

// PublicPerformanceSummary defines model for PublicPerformanceSummary.
type PublicPerformanceSummary struct {
	// FromPrice Integer minor units + ISO-4217 code (ADR-001); no floats, ever
	FromPrice Money              `json:"from_price"`
	Id        openapi_types.UUID `json:"id"`
	StartsAt  time.Time          `json:"starts_at"`
	Timezone  string             `json:"timezone"`
	VenueName string             `json:"venue_name"`
}

// PublicSeasonDetail defines model for PublicSeasonDetail.
type PublicSeasonDetail struct {
	Events      []PublicEventDetail `json:"events"`
	Id          openapi_types.UUID  `json:"id"`
	Name        string              `json:"name"`
	OrganizerId openapi_types.UUID  `json:"organizer_id"`
}

// PublicSeriesContext defines model for PublicSeriesContext.
type PublicSeriesContext struct {
	Id             openapi_types.UUID   `json:"id"`
	Name           string               `json:"name"`
	PerformanceIds []openapi_types.UUID `json:"performance_ids"`
}

// PublicTicketType defines model for PublicTicketType.
type PublicTicketType struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Price Integer minor units + ISO-4217 code (ADR-001); no floats, ever
	Price Money `json:"price"`
}

// PublicVenue defines model for PublicVenue.
type PublicVenue struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// ReEntryPolicy How many admissions one entitlement grants on the slot (spike §Case 1). 'single' is the performance case; 'count_limited' requires max_entries.
type ReEntryPolicy struct {
	MaxEntries   *int32            `json:"max_entries,omitempty"`
	Mode         ReEntryPolicyMode `json:"mode"`
	RequiresExit bool              `json:"requires_exit"`
}

// ReEntryPolicyMode defines model for ReEntryPolicy.Mode.
type ReEntryPolicyMode string

// Season defines model for Season.
type Season struct {
	CreatedAt time.Time            `json:"created_at"`
	EventIds  []openapi_types.UUID `json:"event_ids"`
	Id        openapi_types.UUID   `json:"id"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString      `json:"name"`
	OrganizerId openapi_types.UUID   `json:"organizer_id"`
	SeriesIds   []openapi_types.UUID `json:"series_ids"`
}

// SeasonCreate defines model for SeasonCreate.
type SeasonCreate struct {
	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString    `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// SeasonEventAttach defines model for SeasonEventAttach.
type SeasonEventAttach struct {
	EventId openapi_types.UUID `json:"event_id"`
}

// SeasonSeriesAttach defines model for SeasonSeriesAttach.
type SeasonSeriesAttach struct {
	SeriesId openapi_types.UUID `json:"series_id"`
}

// Series defines model for Series.
type Series struct {
	CreatedAt time.Time          `json:"created_at"`
	EventId   openapi_types.UUID `json:"event_id"`
	Id        openapi_types.UUID `json:"id"`
	Members   []SeriesMember     `json:"members"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString    `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// SeriesCreate defines model for SeriesCreate.
type SeriesCreate struct {
	EventId openapi_types.UUID `json:"event_id"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name        LocalizedString    `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// SeriesLifecycleResult defines model for SeriesLifecycleResult.
type SeriesLifecycleResult struct {
	Performances []Performance      `json:"performances"`
	SeriesId     openapi_types.UUID `json:"series_id"`
}

// SeriesMember defines model for SeriesMember.
type SeriesMember struct {
	PerformanceId openapi_types.UUID `json:"performance_id"`
	Position      int32              `json:"position"`
}

// SeriesPerformanceAttach defines model for SeriesPerformanceAttach.
type SeriesPerformanceAttach struct {
	PerformanceId openapi_types.UUID `json:"performance_id"`
	Position      int32              `json:"position"`
}

// SeriesTransitionConflict defines model for SeriesTransitionConflict.
type SeriesTransitionConflict struct {
	BlockingPerformanceId *openapi_types.UUID `json:"blocking_performance_id,omitempty"`
	Error                 string              `json:"error"`
	Reason                string              `json:"reason"`
}

// SlotCloseRequest Optional operator-supplied reason for the closure
type SlotCloseRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// SlotKind The dated-slot kind (ADR-005 amendment / US-009). 'performance' carries starts_at; 'festival_day'/'operating_day' carry the operating window.
type SlotKind string

// TicketType defines model for TicketType.
type TicketType struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name          LocalizedString    `json:"name"`
	OrganizerId   openapi_types.UUID `json:"organizer_id"`
	PerformanceId openapi_types.UUID `json:"performance_id"`

	// Price Integer minor units + ISO-4217 code (ADR-001); no floats, ever
	Price Money `json:"price"`
}

// TicketTypeCreate defines model for TicketTypeCreate.
type TicketTypeCreate struct {
	// Name Locale-keyed text; adding a locale is data, not a schema change (TKT-36)
	Name          LocalizedString    `json:"name"`
	OrganizerId   openapi_types.UUID `json:"organizer_id"`
	PerformanceId openapi_types.UUID `json:"performance_id"`

	// Price Integer minor units + ISO-4217 code (ADR-001); no floats, ever
	Price Money `json:"price"`
}

// Venue defines model for Venue.
type Venue struct {
	CreatedAt   time.Time          `json:"created_at"`
	GaCapacity  int32              `json:"ga_capacity"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// VenueCreate defines model for VenueCreate.
type VenueCreate struct {
	GaCapacity  int32              `json:"ga_capacity"`
	Name        string             `json:"name"`
	OrganizerId openapi_types.UUID `json:"organizer_id"`
}

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// Locale defines model for Locale.
type Locale = string

// PerformanceId defines model for PerformanceId.
type PerformanceId = openapi_types.UUID

// SeasonId defines model for SeasonId.
type SeasonId = openapi_types.UUID

// SeriesId defines model for SeriesId.
type SeriesId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListPublicEventsParams defines parameters for ListPublicEvents.
type ListPublicEventsParams struct {
	// Locale BCP-47 primary subtag; supported set is data, not schema (TKT-36)
	Locale Locale `form:"locale" json:"locale"`
}

// GetPublicEventParams defines parameters for GetPublicEvent.
type GetPublicEventParams struct {
	// Locale BCP-47 primary subtag; supported set is data, not schema (TKT-36)
	Locale Locale `form:"locale" json:"locale"`
}

// GetPublicSeasonParams defines parameters for GetPublicSeason.
type GetPublicSeasonParams struct {
	// Locale BCP-47 primary subtag; supported set is data, not schema (TKT-36)
	Locale Locale `form:"locale" json:"locale"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = EventCreate

// CreatePerformanceJSONRequestBody defines body for CreatePerformance for application/json ContentType.
type CreatePerformanceJSONRequestBody = PerformanceCreate

// CloseSlotJSONRequestBody defines body for CloseSlot for application/json ContentType.
type CloseSlotJSONRequestBody = SlotCloseRequest

// CreateSeasonJSONRequestBody defines body for CreateSeason for application/json ContentType.
type CreateSeasonJSONRequestBody = SeasonCreate

// AttachEventToSeasonJSONRequestBody defines body for AttachEventToSeason for application/json ContentType.
type AttachEventToSeasonJSONRequestBody = SeasonEventAttach

// AttachSeriesToSeasonJSONRequestBody defines body for AttachSeriesToSeason for application/json ContentType.
type AttachSeriesToSeasonJSONRequestBody = SeasonSeriesAttach

// CreateSeriesJSONRequestBody defines body for CreateSeries for application/json ContentType.
type CreateSeriesJSONRequestBody = SeriesCreate

// AttachPerformanceToSeriesJSONRequestBody defines body for AttachPerformanceToSeries for application/json ContentType.
type AttachPerformanceToSeriesJSONRequestBody = SeriesPerformanceAttach

// CreateTicketTypeJSONRequestBody defines body for CreateTicketType for application/json ContentType.
type CreateTicketTypeJSONRequestBody = TicketTypeCreate

// CreateVenueJSONRequestBody defines body for CreateVenue for application/json ContentType.
type CreateVenueJSONRequestBody = VenueCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an event (localizable content)
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// This contract, as committed (ADR-009)
	// (GET /openapi.yaml)
	GetOpenAPISpec(w http.ResponseWriter, r *http.Request)
	// Create a dated performance (draft)
	// (POST /performances)
	CreatePerformance(w http.ResponseWriter, r *http.Request)
	// Archive a published performance (idempotent)
	// (POST /performances/{performanceId}/archive)
	ArchivePerformance(w http.ResponseWriter, r *http.Request, performanceId PerformanceId)
	// Close a published slot (weather closure; idempotent)
	// (POST /performances/{performanceId}/close)
	CloseSlot(w http.ResponseWriter, r *http.Request, performanceId PerformanceId)
	// Publish a performance (idempotent)
	// (POST /performances/{performanceId}/publish)
	PublishPerformance(w http.ResponseWriter, r *http.Request, performanceId PerformanceId)
	// Reopen a closed slot (idempotent)
	// (POST /performances/{performanceId}/reopen)
	ReopenSlot(w http.ResponseWriter, r *http.Request, performanceId PerformanceId)
	// Aggregated storefront list read (minutes tier)
	// (GET /public/events)
	ListPublicEvents(w http.ResponseWriter, r *http.Request, params ListPublicEventsParams)
	// Aggregated storefront detail read (minutes tier)
	// (GET /public/events/{eventId})
	GetPublicEvent(w http.ResponseWriter, r *http.Request, eventId EventId, params GetPublicEventParams)
	// Aggregated public season detail (minutes tier)
	// (GET /public/seasons/{seasonId})
	GetPublicSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId, params GetPublicSeasonParams)
	// Create a localized season
	// (POST /seasons)
	CreateSeason(w http.ResponseWriter, r *http.Request)
	// Attach a standalone event to a season
	// (POST /seasons/{seasonId}/events)
	AttachEventToSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId)
	// Attach a series to a season
	// (POST /seasons/{seasonId}/series)
	AttachSeriesToSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId)
	// Create a localized series for one event
	// (POST /series)
	CreateSeries(w http.ResponseWriter, r *http.Request)
	// Atomically archive every published slot in the series
	// (POST /series/{seriesId}/archive)
	ArchiveSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId)
	// Attach an ordered draft slot to a series
	// (POST /series/{seriesId}/performances)
	AttachPerformanceToSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId)
	// Atomically publish every slot in the series
	// (POST /series/{seriesId}/publish)
	PublishSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId)
	// Create a ticket type with a price
	// (POST /ticket-types)
	CreateTicketType(w http.ResponseWriter, r *http.Request)
	// Create a general-admission venue
	// (POST /venues)
	CreateVenue(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create an event (localizable content)
// (POST /events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This contract, as committed (ADR-009)
// (GET /openapi.yaml)
func (_ Unimplemented) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a dated performance (draft)
// (POST /performances)
func (_ Unimplemented) CreatePerformance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archive a published performance (idempotent)
// (POST /performances/{performanceId}/archive)
func (_ Unimplemented) ArchivePerformance(w http.ResponseWriter, r *http.Request, performanceId PerformanceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Close a published slot (weather closure; idempotent)
// (POST /performances/{performanceId}/close)
func (_ Unimplemented) CloseSlot(w http.ResponseWriter, r *http.Request, performanceId PerformanceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a performance (idempotent)
// (POST /performances/{performanceId}/publish)
func (_ Unimplemented) PublishPerformance(w http.ResponseWriter, r *http.Request, performanceId PerformanceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reopen a closed slot (idempotent)
// (POST /performances/{performanceId}/reopen)
func (_ Unimplemented) ReopenSlot(w http.ResponseWriter, r *http.Request, performanceId PerformanceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregated storefront list read (minutes tier)
// (GET /public/events)
func (_ Unimplemented) ListPublicEvents(w http.ResponseWriter, r *http.Request, params ListPublicEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregated storefront detail read (minutes tier)
// (GET /public/events/{eventId})
func (_ Unimplemented) GetPublicEvent(w http.ResponseWriter, r *http.Request, eventId EventId, params GetPublicEventParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregated public season detail (minutes tier)
// (GET /public/seasons/{seasonId})
func (_ Unimplemented) GetPublicSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId, params GetPublicSeasonParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a localized season
// (POST /seasons)
func (_ Unimplemented) CreateSeason(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach a standalone event to a season
// (POST /seasons/{seasonId}/events)
func (_ Unimplemented) AttachEventToSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach a series to a season
// (POST /seasons/{seasonId}/series)
func (_ Unimplemented) AttachSeriesToSeason(w http.ResponseWriter, r *http.Request, seasonId SeasonId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a localized series for one event
// (POST /series)
func (_ Unimplemented) CreateSeries(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Atomically archive every published slot in the series
// (POST /series/{seriesId}/archive)
func (_ Unimplemented) ArchiveSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach an ordered draft slot to a series
// (POST /series/{seriesId}/performances)
func (_ Unimplemented) AttachPerformanceToSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Atomically publish every slot in the series
// (POST /series/{seriesId}/publish)
func (_ Unimplemented) PublishSeries(w http.ResponseWriter, r *http.Request, seriesId SeriesId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a ticket type with a price
// (POST /ticket-types)
func (_ Unimplemented) CreateTicketType(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a general-admission venue
// (POST /venues)
func (_ Unimplemented) CreateVenue(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPISpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePerformance operation middleware
func (siw *ServerInterfaceWrapper) CreatePerformance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePerformance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchivePerformance operation middleware
func (siw *ServerInterfaceWrapper) ArchivePerformance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "performanceId" -------------
	var performanceId PerformanceId

	err = runtime.BindStyledParameterWithOptions("simple", "performanceId", chi.URLParam(r, "performanceId"), &performanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchivePerformance(w, r, performanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseSlot operation middleware
func (siw *ServerInterfaceWrapper) CloseSlot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "performanceId" -------------
	var performanceId PerformanceId

	err = runtime.BindStyledParameterWithOptions("simple", "performanceId", chi.URLParam(r, "performanceId"), &performanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseSlot(w, r, performanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishPerformance operation middleware
func (siw *ServerInterfaceWrapper) PublishPerformance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "performanceId" -------------
	var performanceId PerformanceId

	err = runtime.BindStyledParameterWithOptions("simple", "performanceId", chi.URLParam(r, "performanceId"), &performanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishPerformance(w, r, performanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReopenSlot operation middleware
func (siw *ServerInterfaceWrapper) ReopenSlot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "performanceId" -------------
	var performanceId PerformanceId

	err = runtime.BindStyledParameterWithOptions("simple", "performanceId", chi.URLParam(r, "performanceId"), &performanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReopenSlot(w, r, performanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPublicEvents operation middleware
func (siw *ServerInterfaceWrapper) ListPublicEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicEventsParams

	// ------------- Required query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locale"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPublicEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicEvent operation middleware
func (siw *ServerInterfaceWrapper) GetPublicEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicEventParams

	// ------------- Required query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locale"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicEvent(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicSeason operation middleware
func (siw *ServerInterfaceWrapper) GetPublicSeason(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seasonId" -------------
	var seasonId SeasonId

	err = runtime.BindStyledParameterWithOptions("simple", "seasonId", chi.URLParam(r, "seasonId"), &seasonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seasonId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicSeasonParams

	// ------------- Required query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locale"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicSeason(w, r, seasonId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSeason operation middleware
func (siw *ServerInterfaceWrapper) CreateSeason(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSeason(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachEventToSeason operation middleware
func (siw *ServerInterfaceWrapper) AttachEventToSeason(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seasonId" -------------
	var seasonId SeasonId

	err = runtime.BindStyledParameterWithOptions("simple", "seasonId", chi.URLParam(r, "seasonId"), &seasonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seasonId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachEventToSeason(w, r, seasonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachSeriesToSeason operation middleware
func (siw *ServerInterfaceWrapper) AttachSeriesToSeason(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seasonId" -------------
	var seasonId SeasonId

	err = runtime.BindStyledParameterWithOptions("simple", "seasonId", chi.URLParam(r, "seasonId"), &seasonId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seasonId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachSeriesToSeason(w, r, seasonId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSeries operation middleware
func (siw *ServerInterfaceWrapper) CreateSeries(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSeries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveSeries operation middleware
func (siw *ServerInterfaceWrapper) ArchiveSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId SeriesId

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", chi.URLParam(r, "seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachPerformanceToSeries operation middleware
func (siw *ServerInterfaceWrapper) AttachPerformanceToSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId SeriesId

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", chi.URLParam(r, "seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachPerformanceToSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishSeries operation middleware
func (siw *ServerInterfaceWrapper) PublishSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "seriesId" -------------
	var seriesId SeriesId

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", chi.URLParam(r, "seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishSeries(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicketType operation middleware
func (siw *ServerInterfaceWrapper) CreateTicketType(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicketType(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVenue operation middleware
func (siw *ServerInterfaceWrapper) CreateVenue(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVenue(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/openapi.yaml", wrapper.GetOpenAPISpec)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances", wrapper.CreatePerformance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances/{performanceId}/archive", wrapper.ArchivePerformance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances/{performanceId}/close", wrapper.CloseSlot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances/{performanceId}/publish", wrapper.PublishPerformance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances/{performanceId}/reopen", wrapper.ReopenSlot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/public/events", wrapper.ListPublicEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/public/events/{eventId}", wrapper.GetPublicEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/public/seasons/{seasonId}", wrapper.GetPublicSeason)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/seasons", wrapper.CreateSeason)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/seasons/{seasonId}/events", wrapper.AttachEventToSeason)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/seasons/{seasonId}/series", wrapper.AttachSeriesToSeason)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series", wrapper.CreateSeries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series/{seriesId}/archive", wrapper.ArchiveSeries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series/{seriesId}/performances", wrapper.AttachPerformanceToSeries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series/{seriesId}/publish", wrapper.PublishSeries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ticket-types", wrapper.CreateTicketType)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/venues", wrapper.CreateVenue)
	})

	return r
}
