// The back office's access client: the ticket bundle behind a guest reference
// (TKT-193), with the QR credential removed.
import type { components } from './access-api-types.gen';
import {
  GATEWAY_URL,
  type Read,
  readJson,
  boolean,
  dateTime,
  positiveWholeNumber,
  required,
  responseObject,
  sameIdentity,
  uuid,
  withUpstreamDeadline,
} from './upstream';

const access = (path: string) => `${GATEWAY_URL}/api/access${path}`;

type AccessTicketBundle = components['schemas']['TicketBundle'];
type AccessTicket = components['schemas']['Ticket'];
type AccessLifecycleEvent = components['schemas']['LifecycleEvent'];
type SafeTicketWire = Pick<AccessTicket, 'ticket_id' | 'issued_at'> & {
  history: AccessLifecycleEvent[];
};
type SafeTicketBundleWire = Pick<AccessTicketBundle, 'order_ref'> & {
  tickets: SafeTicketWire[];
};

function decodeTicketBundle(value: unknown): SafeTicketBundleWire {
  const body = responseObject(value, 'ticket bundle');
  if (!Array.isArray(body.tickets)) throw new Error('response is missing tickets');
  return {
    order_ref: uuid(body.order_ref, 'order_ref'),
    tickets: body.tickets.map((rawTicket) => {
      const ticket = responseObject(rawTicket, 'ticket');
      if (!Array.isArray(ticket.history)) throw new Error('ticket history is missing or not a list');
      return {
        ticket_id: uuid(ticket.ticket_id, 'ticket_id'),
        issued_at: dateTime(ticket.issued_at, 'issued_at'),
        history: ticket.history.map((rawEvent) => {
          const event = responseObject(rawEvent, 'lifecycle event');
          if (
            event.sequence !== undefined &&
            (typeof event.sequence !== 'number' || !Number.isSafeInteger(event.sequence) || event.sequence < 1)
          ) {
            throw new Error('lifecycle sequence is not a chain position');
          }
          return {
            id: uuid(event.id, 'event id'),
            type: required(event.type, 'event type'),
            sequence: event.sequence as number | undefined,
            occurred_at: dateTime(event.occurred_at, 'occurred_at'),
          };
        }),
      };
    }),
  };
}

export type LifecycleEvent = {
  id: string;
  type: string;
  /** Absent on legacy rows the chain backfill has not adopted (ADR-025 §D5). */
  sequence?: number;
  occurredAt: string;
};
export type SafeTicket = { ticketId: string; issuedAt: string; history: LifecycleEvent[] };

/**
 * The ticket bundle, with the QR credential removed.
 *
 * Access returns `qr_payload` — the value a scanner admits on — and `qr_url`,
 * which points at an endpoint the gateway serves WITHOUT authentication. Either
 * one rendered on a staff console is a working ticket for someone else's order,
 * and it survives in screenshots and support transcripts long after the visit.
 * The allow-list is here rather than in the page so that no page, present or
 * future, can render what it was never handed.
 */
export function getOrderTickets(ref: string): Promise<Read<SafeTicket[]>> {
  return readJson(access(`/orders/${encodeURIComponent(ref)}/tickets`), (body) => {
    const bundle = decodeTicketBundle(body);
    sameIdentity(bundle.order_ref, ref, 'order_ref');
    return bundle.tickets.map((ticket) => ({
      ticketId: ticket.ticket_id,
      issuedAt: ticket.issued_at,
      history: ticket.history.map((event) => ({
        id: event.id,
        type: event.type,
        sequence: event.sequence,
        occurredAt: event.occurred_at,
      })),
    }));
  });
}

/**
 * The back office's access credential (TKT-203, ADR-068).
 *
 * Read through a function rather than a module constant so a missing value fails on the
 * first resend with a message naming the variable, instead of silently sending
 * `undefined` and surfacing as access's deliberately uninformative 404.
 *
 * Never `X-Internal-Token`: that one value opens every service's internal surface and is
 * deliberately withheld from this process (compose.yaml, and pinned by api.test.ts).
 */
function accessStaffCredential(): string {
  const token = process.env.ACCESS_STAFF_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      "ACCESS_STAFF_WRITE_TOKEN is not set: the back office cannot re-send an order's tickets. " +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  return token;
}

/**
 * DIRECT to access, not through the gateway — unlike getOrderTickets above, which reads
 * a public route. The resend lives under `/internal/`, which the gateway edge-denies by
 * construction (ADR-002: the route table is the security boundary). The credential is
 * the boundary here; the network path is not. The staff refund reaches commerce this way
 * (TKT-194) and the allocation editor reaches inventory this way (TKT-244).
 */
const ACCESS_URL = process.env.ACCESS_URL ?? 'http://localhost:8084';

export type Redelivery = { orderId: string; ticketCount: number; replay: boolean };

/**
 * Why four failure kinds and not two.
 *
 * `not-found`, `refused` and `too-many` are DECIDED: access looked and said no, so the
 * page can state it and the operator knows what to do next. `ambiguous` is a 5xx or a
 * success whose body we could not verify — the mail **may have gone out**, and the only
 * honest thing to render is "retry this exact request", with the idempotency key
 * preserved so the retry is a replay rather than a second send.
 *
 * `not-yet` is separate from `not-found` because they call for opposite actions:
 * issuance is asynchronous, so a resend seconds after checkout can genuinely arrive
 * first. Telling an operator "no such order" then would send them looking for a problem
 * that does not exist; the right advice is to wait a moment and try again.
 */
export type RedeliveryOutcome =
  | { ok: true; value: Redelivery }
  | { ok: false; kind: 'not-found' | 'refused' | 'too-many' | 'not-yet' | 'ambiguous'; message: string };

export type RedeliveryRequest = {
  orderId: string;
  /** From the session. Never from the form — see the organizer note in orders.astro. */
  organizerId: string;
  idempotencyKey: string;
};

/**
 * Re-send a completed order's tickets to the address ON FILE.
 *
 * THERE IS NO RECIPIENT PARAMETER, and its absence is the security property rather than
 * an omission. Access resolves the address from each ticket's buyer at send time. An
 * operator-typed destination would turn this process into a relay emitting ticket
 * capabilities to arbitrary recipients — the owner's decision (2026-08-26) refuses that,
 * and the way to refuse it is to make it unsubmittable rather than validated.
 *
 * The response carries a COUNT, never the address and never a ticket link. Nothing here
 * can render what it was never handed — the same reasoning as the QR allow-list above.
 */
export async function redeliverOrderTickets(req: RedeliveryRequest): Promise<RedeliveryOutcome> {
  // OUTSIDE the try. A missing credential is a configuration defect, and reporting it as
  // an ambiguous access outage would tell the operator to retry a request that can never
  // succeed.
  const credential = accessStaffCredential();
  try {
    return await withUpstreamDeadline(async (signal) => {
      const res = await fetch(
        `${ACCESS_URL}/internal/orders/${encodeURIComponent(req.orderId)}/redeliveries`,
        {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'Idempotency-Key': req.idempotencyKey,
            'X-Access-Staff-Write-Token': credential,
          },
          body: JSON.stringify({ organizer_id: req.organizerId }),
          signal,
        },
      );

      const message = await accessMessage(res);
      if (res.status === 404) return { ok: false, kind: 'not-found', message };
      if (res.status === 503) return { ok: false, kind: 'not-yet', message };
      if (res.status === 429) return { ok: false, kind: 'too-many', message };
      if (res.status === 400 || res.status === 409) return { ok: false, kind: 'refused', message };
      if (!res.ok) return { ok: false, kind: 'ambiguous', message };

      try {
        const b = responseObject(await res.json(), 'ticket redelivery');
        const orderId = uuid(b.order_id, 'order_id');
        // The order it answers about must be the order asked about. A mismatch is a
        // response this client does not understand, and rendering "re-sent" against
        // the wrong order id is worse than reporting the ambiguity.
        sameIdentity(orderId, req.orderId, 'order_id');
        const ticketCount = positiveWholeNumber(b.ticket_count, 'ticket_count');
        if (ticketCount > 50) throw new Error('ticket_count is above the contract maximum');
        return { ok: true, value: { orderId, ticketCount, replay: boolean(b.replay, 'replay') } };
      } catch (err) {
        // A 200 we could not read. The mail went out; only our understanding of the
        // answer failed, so this is ambiguous rather than refused.
        return {
          ok: false,
          kind: 'ambiguous',
          message: err instanceof Error ? err.message : 'unreadable response',
        };
      }
    });
  } catch {
    return { ok: false, kind: 'ambiguous', message: 'access did not answer in time.' };
  }
}

/**
 * Access's error bodies are `{error: string}`. Read defensively: an unreadable body must
 * not turn a decided refusal into a thrown exception on the page.
 */
async function accessMessage(res: Response): Promise<string> {
  try {
    const b = responseObject(await res.clone().json(), 'access error');
    if (typeof b.error === 'string' && b.error) return b.error;
  } catch {
    /* fall through */
  }
  return `access answered ${res.status}.`;
}
