// Catalog reads, through the gateway (the back-office consumes the public
// contract, ADR-002/ADR-009). Types are generated from the catalog's OpenAPI
// document — regenerate with `make generate`.
import type { components } from './api-types.gen';
import { isRecognisedRole, type StaffRole } from './authorization';

export type Venue = components['schemas']['Venue'];
export type PublicVenueList = components['schemas']['PublicVenueList'];
export type SeatMap = components['schemas']['SeatMap'];
export type SeatMapList = components['schemas']['SeatMapList'];
export type SeatMapGeometry = components['schemas']['SeatMapGeometry'];
export type SeatSection = components['schemas']['SeatSection'];
export type SeatRow = components['schemas']['SeatRow'];
export type Seat = components['schemas']['Seat'];
export type SeatMapEdit = components['schemas']['SeatMapEdit'];
export type SeatMapVersionHistory = components['schemas']['SeatMapVersionHistory'];

// CatalogApiError carries the catalog's parsed { error } message and HTTP status
// (emulating the storefront's UpstreamError) so the UI can show an actionable
// message — e.g. the TKT-104 pinning-contract rejection — instead of a bare
// status code.
export class CatalogApiError extends Error {
  constructor(
    public readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = 'CatalogApiError';
  }
}

const GATEWAY_URL = process.env.GATEWAY_URL ?? 'http://localhost:8080';

/**
 * The back office's credential for catalog writes (TKT-191, ADR-042). Catalog
 * authenticates the DEPUTY — it knows the caller is this process; which staff
 * member may drive which write is decided here, by the session gate (roles are
 * TKT-197).
 *
 * Read through a function rather than a module constant so a missing value
 * fails on the first write with a message naming the variable, instead of
 * silently sending `undefined` and surfacing as catalog's deliberately
 * uninformative 401 — which is indistinguishable from a wrong password on the
 * sign-in path.
 */
function staffWriteCredential(): string {
  const token = process.env.CATALOG_STAFF_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'CATALOG_STAFF_WRITE_TOKEN is not set: the back office cannot write to catalog. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  return token;
}

/** Headers for every catalog write. One helper, so no call site can forget. */
function writeHeaders(): Record<string, string> {
  return {
    'content-type': 'application/json',
    'X-Catalog-Staff-Write-Token': staffWriteCredential(),
  };
}

// v1 has a single organizer (US-002 AC5); the fixed UUID is seeded by the
// catalog migration (0002). When admin auth lands this comes from the session.
export const DEFAULT_ORGANIZER_ID = '00000000-0000-0000-0000-000000000001';

/** The venue list page's single read: the organizer's venues (hours tier). */
export async function getVenues(organizerId = DEFAULT_ORGANIZER_ID): Promise<Venue[]> {
  const url = `${GATEWAY_URL}/api/catalog/public/venues?organizer_id=${encodeURIComponent(organizerId)}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`catalog venue read failed: ${res.status}`);
  }
  const body = (await res.json()) as PublicVenueList;
  return body.venues;
}

/** One venue by id (v1 has no single-venue read; filter the organizer list). */
export async function getVenue(
  venueId: string,
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<Venue | undefined> {
  const venues = await getVenues(organizerId);
  return venues.find((v) => v.id === venueId);
}

const catalog = (path: string) => `${GATEWAY_URL}/api/catalog${path}`;

// parseError pulls the catalog's { error } message off a non-2xx response so the
// UI can surface it; falls back to a generic line if the body is not the shared
// Error shape. Never throws while reading the body.
async function parseError(res: Response): Promise<CatalogApiError> {
  let message = `catalog request failed: ${res.status}`;
  try {
    const body = (await res.json()) as { error?: unknown };
    if (body && typeof body.error === 'string' && body.error) {
      message = body.error;
    }
  } catch {
    // non-JSON body — keep the generic message
  }
  return new CatalogApiError(res.status, message);
}

async function postCatalog<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(catalog(path), {
    method: 'POST',
    headers: writeHeaders(),
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw await parseError(res);
  }
  return (await res.json()) as T;
}

// --- Seat-map authoring (US-019). Writes go through the gateway server-side,
// same posture as the reads; the browser never talks to the gateway directly. ---

export function createSeatMap(
  venueId: string,
  name: string,
  // Orphan-seat prevention (ADR-041). Defaults off so an existing caller creates
  // exactly the map it created before; the flag is per version, and an edit that
  // omits it inherits rather than clears.
  orphanPreventionEnabled = false,
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<SeatMap> {
  return postCatalog<SeatMap>(`/venues/${encodeURIComponent(venueId)}/seat-maps`, {
    organizer_id: organizerId,
    name,
    orphan_prevention_enabled: orphanPreventionEnabled,
  });
}

export function addSeatMapSection(
  seatMapId: string,
  section: { name: string; position: number },
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<SeatSection> {
  return postCatalog<SeatSection>(`/seat-maps/${encodeURIComponent(seatMapId)}/sections`, {
    organizer_id: organizerId,
    ...section,
  });
}

export function addSeatMapRow(
  seatMapId: string,
  row: { section_id: string; label: string; position: number },
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<SeatRow> {
  return postCatalog<SeatRow>(`/seat-maps/${encodeURIComponent(seatMapId)}/rows`, {
    organizer_id: organizerId,
    ...row,
  });
}

export function addSeatMapSeat(
  seatMapId: string,
  seat: { row_id: string; label: string; position: number },
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<Seat> {
  return postCatalog<Seat>(`/seat-maps/${encodeURIComponent(seatMapId)}/seats`, {
    organizer_id: organizerId,
    ...seat,
  });
}

/**
 * A venue's seat-map summaries, for the venue page. Cache tier is status-driven
 * (TKT-107): hours only when every map listed is published, else no-store. This
 * read goes through plain uncached fetch, so the header is informational here.
 */
export async function listVenueSeatMaps(venueId: string): Promise<SeatMap[]> {
  const res = await fetch(catalog(`/public/venues/${encodeURIComponent(venueId)}/seat-maps`));
  if (!res.ok) {
    throw new Error(`seat-map list failed: ${res.status}`);
  }
  return ((await res.json()) as SeatMapList).seat_maps;
}

/**
 * One seat map's full geometry. Cache tier is status-driven (TKT-107): a
 * published version is hours-tier, a draft is no-store.
 */
export async function getSeatMapGeometry(seatMapId: string): Promise<SeatMapGeometry> {
  const res = await fetch(catalog(`/public/seat-maps/${encodeURIComponent(seatMapId)}`));
  if (!res.ok) {
    throw new Error(`seat-map geometry read failed: ${res.status}`);
  }
  return (await res.json()) as SeatMapGeometry;
}

// --- Publishing, safe-editing, versioning, GA config (US-020/021/022, TKT-105).
// Editing surfaces the TKT-104 store contract over the new catalog endpoint; the
// UI adds no domain logic. ---

/** Publish a draft map (TKT-103). Idempotent server-side. */
export function publishSeatMap(seatMapId: string): Promise<SeatMap> {
  return postCatalog<SeatMap>(`/seat-maps/${encodeURIComponent(seatMapId)}/publish`, null);
}

/**
 * Edit a published map, producing a new version (TKT-105). `edit` is the FULL
 * replacement geometry; seatMapId may be any version of the family. A rejected
 * edit (would orphan a pinned seat) throws a CatalogApiError carrying the
 * actionable {error} message and 409 status.
 */
export function editSeatMap(seatMapId: string, edit: SeatMapEdit): Promise<SeatMap> {
  return postCatalog<SeatMap>(`/seat-maps/${encodeURIComponent(seatMapId)}/edit`, edit);
}

/**
 * A seat-map family's version history; resolves from any version id. Cache tier is
 * status-driven (TKT-107): hours only when every version listed is published.
 */
export async function listSeatMapVersions(seatMapId: string): Promise<SeatMapVersionHistory> {
  const res = await fetch(catalog(`/public/seat-maps/${encodeURIComponent(seatMapId)}/versions`));
  if (!res.ok) {
    throw await parseError(res);
  }
  return (await res.json()) as SeatMapVersionHistory;
}

/** Set a venue's GA capacity (TKT-105 COS-5). */
export function updateVenueGaCapacity(
  venueId: string,
  gaCapacity: number,
  organizerId = DEFAULT_ORGANIZER_ID,
): Promise<Venue> {
  return postCatalog<Venue>(`/venues/${encodeURIComponent(venueId)}/ga-capacity`, {
    organizer_id: organizerId,
    ga_capacity: gaCapacity,
  });
}

// --- Staff sign-in (TKT-190 / US-B1) ---

/** Who is signed in. Carries no role: TKT-191 owns role semantics. */
export interface StaffPrincipalDto {
  staffId: string;
  organizerId: string;
  role: StaffRole;
}

/**
 * Verify a staff credential. Returns null for "those credentials are wrong" —
 * an expected answer to a sign-in attempt, not an exceptional one — and throws
 * for anything else, so an outage can never be rendered as a bad password.
 *
 * Goes through the gateway like every other call in this file. The catalog's
 * authenticate operation is public precisely so this stays true: reaching an
 * internal-token endpoint would mean shipping the shared service credential into
 * the back-office container, and that one token also opens commerce's refunds
 * and inventory's operational holds (ADR-042).
 */
export async function authenticateStaff(
  identifier: string,
  password: string,
): Promise<StaffPrincipalDto | null> {
  const res = await fetch(catalog('/staff/authenticate'), {
    method: 'POST',
    // Guarded like every other unsafe operation (TKT-191). ADR-042 originally
    // made this endpoint public to avoid putting the SHARED service token in
    // this process; a catalog-only credential removes that objection, and
    // leaving it unguarded would mean an exception list inside a fail-closed
    // scheme.
    headers: writeHeaders(),
    // In the body, never the URL: a query string lands in access logs, proxy
    // logs and browser history.
    body: JSON.stringify({ identifier, password }),
  });
  if (res.status === 401) {
    return null;
  }
  if (!res.ok) {
    throw await parseError(res);
  }
  const body = (await res.json()) as { staff_id: string; organizer_id: string; role: string };
  if (!isRecognisedRole(body.role)) {
    // Catalog validates the stored role too, so reaching this means the contract
    // and this client disagree about the vocabulary — a deployment skew. Refuse
    // rather than mint a session carrying a role the matrix cannot classify:
    // fail-closed at every layer that handles a role is the whole design.
    throw new Error(`catalog returned an unrecognised staff role`);
  }
  return { staffId: body.staff_id, organizerId: body.organizer_id, role: body.role };
}

// --- Event authoring (TKT-192 / US-B3) ---
//
// Four thin wrappers over postCatalog, which already attaches the staff-write
// credential (TKT-191) and turns a non-2xx into a CatalogApiError carrying
// catalog's own {error} message. The builder page surfaces that message
// verbatim, so a refusal catalog decides (ADR-018) reads as a sentence rather
// than a status code.
//
// The organizer is a parameter on every one of these, never a default: it comes
// from the session (TKT-190), and a default here is how one organizer's staff
// would author into another's tenant.

export type Event = components['schemas']['Event'];
export type Performance = components['schemas']['Performance'];
export type TicketType = components['schemas']['TicketType'];
export type LocalizedStringDto = components['schemas']['LocalizedString'];

export function createEvent(organizerId: string, name: LocalizedStringDto): Promise<Event> {
  return postCatalog<Event>('/events', { organizer_id: organizerId, name });
}

export function createPerformance(
  organizerId: string,
  input: { eventId: string; venueId: string; startsAt: string; timezone: string },
): Promise<Performance> {
  return postCatalog<Performance>('/performances', {
    organizer_id: organizerId,
    event_id: input.eventId,
    venue_id: input.venueId,
    // RFC 3339 with an explicit offset, and the IANA zone alongside it. A
    // `datetime-local` value carries no zone, and converting one in the SERVER's
    // zone would shift every slot for any organizer who is not sitting next to
    // the server — silently, and only for them.
    starts_at: input.startsAt,
    timezone: input.timezone,
  });
}

export function createTicketType(
  organizerId: string,
  input: { performanceId: string; name: LocalizedStringDto; amount: number; currency: string },
): Promise<TicketType> {
  return postCatalog<TicketType>('/ticket-types', {
    organizer_id: organizerId,
    performance_id: input.performanceId,
    name: input.name,
    // Integer minor units + ISO code, parsed as such (ADR-001). Nothing on this
    // path has ever been a float.
    price: { amount: input.amount, currency: input.currency },
  });
}

/**
 * Publish a draft slot. Catalog owns the decision (ADR-018): a grouped festival
 * day refuses its own publish, an archived slot refuses the transition, and a
 * slot with no ticket type is refused as not sellable. Each arrives here as a
 * CatalogApiError whose message is catalog's own.
 */
export function publishPerformance(performanceId: string): Promise<Performance> {
  return postCatalog<Performance>(
    `/performances/${encodeURIComponent(performanceId)}/publish`,
    null,
  );
}
