// The back office's commerce client: one read (TKT-193) and one write (TKT-194).
//
// The read goes through the gateway like everything else. The refund does NOT —
// see refundOrder.
import {
  GATEWAY_URL,
  type Read,
  boolean,
  readJson,
  required,
  sameIdentity,
  wholeNumber,
} from './upstream';

const commerce = (path: string) => `${GATEWAY_URL}/api/commerce${path}`;

export type OrderState = { orderId: string; status: string };

/** Commerce's order state: `{order_id, status}` and, by contract, nothing else. */
export function getOrderState(orderId: string): Promise<Read<OrderState>> {
  return readJson(commerce(`/orders/${encodeURIComponent(orderId)}`), (body) => {
    const b = body as { order_id?: unknown; status?: unknown };
    const got = required(b.order_id, 'order_id');
    sameIdentity(got, orderId, 'order_id');
    return { orderId: got, status: required(b.status, 'status') };
  });
}

// ---------------------------------------------------------------------------
// The staff refund (TKT-194).
//
// DIRECT to commerce, not through the gateway. The gateway edge-denies every
// `/api/<svc>/internal/` route by construction (ADR-002: the route table is the
// security boundary), and adding a named exception would publish a
// money-moving endpoint to the public internet behind one bearer token — while
// granting this process nothing it does not already have, since it can already
// open a socket to commerce on the container network. The credential is the
// boundary here; the network path is not. Access reaches commerce's internal
// delivery-email read exactly this way.

const COMMERCE_URL = process.env.COMMERCE_URL ?? 'http://localhost:8082';

/**
 * The back office's commerce credential (TKT-194, ADR-042 as amended).
 *
 * Refuses to equal the catalog credential. Two credentials with different blast
 * radii are only two credentials if they hold different values, and equality
 * would mean a leak of the catalog token — which authors events — became a leak
 * of the token that refunds money. Commerce makes the same check against
 * `INTERNAL_SERVICE_TOKEN` at startup; this is the pair only this process holds,
 * so it is the pair only this process can compare (credentials.mjs).
 *
 * Read through a function rather than a module constant so a missing value
 * fails on the first refund with a message naming the variable.
 */
function commerceStaffCredential(): string {
  const token = process.env.COMMERCE_STAFF_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'COMMERCE_STAFF_WRITE_TOKEN is not set: the back office cannot refund. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  return token;
}

export type Refund = {
  refundId: string;
  orderId: string;
  quantity: number;
  amount: number;
  currency: string;
  refundStatus: 'none' | 'partial' | 'full';
  refundedQuantity: number;
  refundedAmount: number;
  replay: boolean;
  ticketsVoided: boolean;
  capacityReturned: boolean;
};

/**
 * Why three failure kinds and not two.
 *
 * `not-found` and `refused` are decided: commerce looked and said no, so the
 * page can state it. `ambiguous` is a 5xx or a success whose body we could not
 * verify — the refund **may have happened**, and the only honest thing to render
 * is "retry this exact request", with the idempotency key preserved so the retry
 * is a replay rather than a second refund.
 */
export type RefundOutcome =
  | { ok: true; value: Refund }
  | { ok: false; kind: 'not-found' | 'refused' | 'ambiguous'; message: string };

export type RefundRequest = {
  orderId: string;
  quantity: number;
  reason: string;
  /** From the session. Never from the form — see COS-5. */
  actor: string;
  organizerId: string;
  idempotencyKey: string;
};

export async function refundOrder(req: RefundRequest): Promise<RefundOutcome> {
  // OUTSIDE the try. A missing credential is a configuration defect, and
  // reporting it as an ambiguous commerce outage would tell the operator to
  // retry a request that can never succeed (ai-review pass 1).
  const credential = commerceStaffCredential();
  let res: Response;
  try {
    res = await fetch(`${COMMERCE_URL}/internal/orders/${encodeURIComponent(req.orderId)}/refunds`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'Idempotency-Key': req.idempotencyKey,
        'X-Commerce-Staff-Write-Token': credential,
      },
      body: JSON.stringify({
        organizer_id: req.organizerId,
        quantity: req.quantity,
        actor: req.actor,
        reason: req.reason,
      }),
    });
  } catch {
    // The request may have reached commerce and been applied. Never "no refund
    // happened".
    return { ok: false, kind: 'ambiguous', message: 'Commerce could not be reached.' };
  }

  const message = await commerceMessage(res);
  if (res.status === 404) return { ok: false, kind: 'not-found', message };
  if (res.status === 400 || res.status === 409) return { ok: false, kind: 'refused', message };
  if (!res.ok) return { ok: false, kind: 'ambiguous', message };

  try {
    const b = (await res.json()) as Record<string, unknown>;
    const orderId = required(b.order_id, 'order_id');
    sameIdentity(orderId, req.orderId, 'order_id');
    const status = required(b.refund_status, 'refund_status');
    if (status !== 'none' && status !== 'partial' && status !== 'full') {
      throw new Error('refund_status is outside the contract enum');
    }
    return {
      ok: true,
      value: {
        refundId: required(b.refund_id, 'refund_id'),
        orderId,
        // Integer minor units throughout (ADR-001). A fractional amount here
        // means someone put a float on a money path.
        quantity: wholeNumber(b.quantity, 'quantity'),
        amount: wholeNumber(b.amount, 'amount'),
        currency: required(b.currency, 'currency'),
        refundStatus: status,
        refundedQuantity: wholeNumber(b.refunded_quantity, 'refunded_quantity'),
        refundedAmount: wholeNumber(b.refunded_amount, 'refunded_amount'),
        replay: boolean(b.replay, 'replay'),
        ticketsVoided: boolean(b.tickets_voided, 'tickets_voided'),
        capacityReturned: boolean(b.capacity_returned, 'capacity_returned'),
      },
    };
  } catch {
    // A 200 we cannot verify is NOT a failure to refund — commerce answered 200.
    // It is a refund we cannot describe, which is exactly the ambiguous case.
    return {
      ok: false,
      kind: 'ambiguous',
      message: 'Commerce accepted the refund but returned something this console cannot read.',
    };
  }
}

async function commerceMessage(res: Response): Promise<string> {
  try {
    const b = (await res.clone().json()) as { error?: unknown };
    if (typeof b.error === 'string' && b.error !== '') return b.error;
  } catch {
    /* fall through to the generic line */
  }
  return `Commerce answered ${res.status}.`;
}
