// Back-office credential separation, checked ONCE at startup (TKT-194).
//
// middleware.ts calls this at MODULE SCOPE, so the check runs when the SSR
// server loads its entry — not on the first refund. The call lives there rather
// than here so this module stays importable by its own test: a module that
// throws on import cannot be tested by importing it.
//
// That distinction is the whole finding (ai-review pass 1). An earlier version
// compared the two credentials inside `refundOrder`, which meant a deployment
// with both set to the same value started normally, passed its healthcheck, and
// served every page: the internet-facing SSR process held one bearer value
// opening BOTH catalog writes and commerce refunds, and nothing anywhere
// noticed. An attacker who compromised the process would use that value
// directly and never call the helper that was supposed to object.
//
// The Go services cannot catch this pair. Catalog compares its credential
// against INTERNAL_SERVICE_TOKEN and commerce compares its own; neither is ever
// given the other's, by design. The back office is the only process that holds
// both, so it is the only one that can compare them.

/** Throws if the back office's two staff credentials are missing or identical. */
export function assertCredentialSeparation(env: NodeJS.ProcessEnv = process.env): void {
  const catalog = env.CATALOG_STAFF_WRITE_TOKEN;
  const commerce = env.COMMERCE_STAFF_WRITE_TOKEN;
  if (!catalog) {
    throw new Error(
      'CATALOG_STAFF_WRITE_TOKEN is not set: the back office cannot write to catalog. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  if (!commerce) {
    throw new Error(
      'COMMERCE_STAFF_WRITE_TOKEN is not set: the back office cannot refund. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  if (catalog === commerce) {
    // Neither value is echoed.
    throw new Error(
      'CATALOG_STAFF_WRITE_TOKEN must not equal COMMERCE_STAFF_WRITE_TOKEN: they exist to have ' +
        'different blast radii — one authors catalog content, the other moves money — and ' +
        'identical values collapse that boundary while looking configured.',
    );
  }
}
