// The back office's inventory client: one read and one write, both for the
// channel-allocation editor (TKT-244, ADR-057).
//
// DIRECT to inventory, not through the gateway. Both operations live under
// `/internal/`, which the gateway edge-denies by construction (ADR-002: the route table
// is the security boundary). Adding a named exception would publish capacity
// configuration to the public internet while granting this process nothing it does not
// already have — it can already open a socket to inventory on the container network. The
// credential is the boundary here; the network path is not. The staff refund reaches
// commerce exactly this way (TKT-194), and the operator channel read reaches catalog this
// way (TKT-236).
//
// A NEW credential rather than a reused one, which is the decision this ticket exists
// for. ADR-053 chose "no new credential" for catalog's operator read three days earlier,
// because that token could ALREADY create and update the channels it was then allowed to
// list — the allowance added amplification but no new capability class. The back office
// holds nothing for inventory, so reusing a catalog credential here would grant power
// across a service boundary and turn a catalog-token leak into an inventory-write leak.

import type { components } from './inventory-api-types.gen';
import type { ChannelAllocationSet } from './allocation-form';
import {
  decodeMutationResponse,
  fetchMutation,
  boolean,
  dateTime,
  nonNegativeWholeNumber,
  positiveWholeNumber,
  required,
  responseArray,
  responseObject,
  sameIdentity,
  uuid,
  withUpstreamDeadline,
} from './upstream';

export type StaffAvailability = components['schemas']['StaffAvailability'];
export type ChannelAvailability = components['schemas']['ChannelAvailability'];
export type ChannelAllocations = components['schemas']['ChannelAllocations'];

const INVENTORY_URL = process.env.INVENTORY_URL ?? 'http://localhost:8081';

/**
 * The back office's inventory credential (TKT-244, ADR-057).
 *
 * Read through a function rather than a module constant so a missing value fails on the
 * first call with a message naming the variable, instead of silently sending `undefined`
 * and surfacing as inventory's deliberately uninformative 401.
 *
 * Never `X-Internal-Token`: that one value opens every service's internal surface and is
 * deliberately withheld from this process (compose.yaml, and pinned by api.test.ts).
 */
function inventoryStaffCredential(): string {
  const token = process.env.INVENTORY_STAFF_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'INVENTORY_STAFF_WRITE_TOKEN is not set: the back office cannot edit channel allocations. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  return token;
}

const headerName = 'X-Inventory-Staff-Write-Token';

/** An inventory refusal the editor can attribute; see allocation-form.ts. */
export class InventoryApiError extends Error {
  constructor(
    public readonly status: number,
    message: string,
    public readonly code?: string,
    public readonly channel?: string,
  ) {
    super(message);
    this.name = 'InventoryApiError';
  }
}

async function refuse(res: Response): Promise<never> {
  let body: Record<string, unknown> = {};
  try {
    body = responseObject(await res.json(), 'inventory error');
  } catch {
    // A body that is not JSON is not a refusal this client can attribute; the status
    // still has to reach the caller.
  }
  throw new InventoryApiError(
    res.status,
    typeof body.error === 'string' && body.error !== ''
      ? body.error
      : `inventory answered ${res.status}`,
    typeof body.code === 'string' && body.code !== '' ? body.code : undefined,
    typeof body.channel === 'string' && body.channel !== '' ? body.channel : undefined,
  );
}

function decodeChannelAllocation(value: unknown): ChannelAllocations['allocations'][number] {
  const body = responseObject(value, 'channel allocation');
  return {
    channel: required(body.channel, 'allocation channel'),
    cap: positiveWholeNumber(body.cap, 'allocation cap'),
    ...(body.release_at === undefined
      ? {}
      : { release_at: dateTime(body.release_at, 'allocation release_at') }),
    ...(body.opens_at === undefined
      ? {}
      : { opens_at: dateTime(body.opens_at, 'allocation opens_at') }),
    ...(body.closes_at === undefined
      ? {}
      : { closes_at: dateTime(body.closes_at, 'allocation closes_at') }),
    requires_code:
      body.requires_code === undefined
        ? false
        : boolean(body.requires_code, 'allocation requires_code'),
    ...(body.sold_by === undefined ? {} : { sold_by: uuid(body.sold_by, 'allocation sold_by') }),
  };
}

function decodeChannelAvailability(value: unknown): ChannelAvailability {
  const body = responseObject(value, 'channel availability');
  return {
    channel: required(body.channel, 'channel availability channel'),
    cap: positiveWholeNumber(body.cap, 'channel availability cap'),
    ...(body.release_at === undefined
      ? {}
      : { release_at: dateTime(body.release_at, 'channel availability release_at') }),
    released: boolean(body.released, 'channel availability released'),
    ...(body.opens_at === undefined
      ? {}
      : { opens_at: dateTime(body.opens_at, 'channel availability opens_at') }),
    ...(body.closes_at === undefined
      ? {}
      : { closes_at: dateTime(body.closes_at, 'channel availability closes_at') }),
    window_open: boolean(body.window_open, 'channel availability window_open'),
    ...(body.requires_code === undefined
      ? {}
      : { requires_code: boolean(body.requires_code, 'channel availability requires_code') }),
    ...(body.sold_by === undefined
      ? {}
      : { sold_by: uuid(body.sold_by, 'channel availability sold_by') }),
    held: nonNegativeWholeNumber(body.held, 'channel availability held'),
    confirmed: nonNegativeWholeNumber(body.confirmed, 'channel availability confirmed'),
    available: nonNegativeWholeNumber(body.available, 'channel availability available'),
  };
}

function decodeStaffAvailability(value: unknown, expectedSlotId: string): StaffAvailability {
  const body = responseObject(value, 'staff availability');
  const slotId = uuid(body.slot_id, 'staff availability slot_id');
  sameIdentity(slotId, expectedSlotId, 'staff availability slot_id');
  const offeringStatus = body.offering_status;
  if (offeringStatus !== 'open' && offeringStatus !== 'closed' && offeringStatus !== 'archived') {
    throw new Error('response offering_status is not recognized');
  }
  return {
    slot_id: slotId,
    capacity: positiveWholeNumber(body.capacity, 'staff availability capacity'),
    ...(body.target_capacity === undefined
      ? {}
      : { target_capacity: positiveWholeNumber(body.target_capacity, 'staff availability target_capacity') }),
    buyer_held: nonNegativeWholeNumber(body.buyer_held, 'staff availability buyer_held'),
    operational_held: nonNegativeWholeNumber(body.operational_held, 'staff availability operational_held'),
    reservation_held: nonNegativeWholeNumber(body.reservation_held, 'staff availability reservation_held'),
    confirmed: nonNegativeWholeNumber(body.confirmed, 'staff availability confirmed'),
    available: nonNegativeWholeNumber(body.available, 'staff availability available'),
    public_available: nonNegativeWholeNumber(body.public_available, 'staff availability public_available'),
    offering_status: offeringStatus,
    channels: responseArray(body.channels, 'staff availability channels').map(decodeChannelAvailability),
    ...(body.allocation_revision === undefined
      ? {}
      : { allocation_revision: nonNegativeWholeNumber(body.allocation_revision, 'allocation_revision') }),
  };
}

function decodeChannelAllocations(value: unknown, expectedSlotId: string): ChannelAllocations {
  const body = responseObject(value, 'channel allocations');
  const slotId = uuid(body.slot_id, 'channel allocations slot_id');
  sameIdentity(slotId, expectedSlotId, 'channel allocations slot_id');
  return {
    slot_id: slotId,
    allocations: responseArray(body.allocations, 'channel allocations').map(decodeChannelAllocation),
  };
}

/**
 * The slot's staff availability: capacity, the derived counters, and one row per channel
 * allocation with its cap, window, gate, seller binding and CURRENT CONSUMPTION.
 *
 * The consumption is a condition of success for the editor — an operator lowering a cap
 * needs to see what the channel has already sold — and this is the only read that reports
 * it. It is also the read that makes a safe round trip possible: the write is a full-set
 * replace, so anything this read does not return is a field the next save destroys.
 */
export async function getStaffAvailability(
  slotId: string,
  organizerId: string,
): Promise<StaffAvailability> {
  const credential = inventoryStaffCredential();
  const url =
    `${INVENTORY_URL}/internal/slots/${encodeURIComponent(slotId)}/availability` +
    `?organizer_id=${encodeURIComponent(organizerId)}`;
  return withUpstreamDeadline(async (signal) => {
    const res = await fetch(url, { headers: { [headerName]: credential }, signal });
    if (!res.ok) return refuse(res);
    return decodeStaffAvailability(await res.json(), slotId);
  });
}

/**
 * Replace the slot's WHOLE allocation set, atomically, under the pool lock (ADR-024).
 *
 * There is no per-row save and there must not be one: the endpoint replaces the complete
 * desired state, so submitting one row would delete every other allocation. The editor
 * therefore always sends every row it read, including rows the operator did not touch.
 */
export async function replaceChannelAllocations(
  slotId: string,
  set: ChannelAllocationSet,
): Promise<ChannelAllocations> {
  const credential = inventoryStaffCredential();
  return withUpstreamDeadline(async (signal) => {
    const res = await fetchMutation(
      'Inventory',
      `${INVENTORY_URL}/internal/slots/${encodeURIComponent(slotId)}/channel-allocations`,
      {
        method: 'PUT',
        headers: { 'content-type': 'application/json', [headerName]: credential },
        body: JSON.stringify(set),
        signal,
      },
    );
    if (!res.ok) return refuse(res);
    return decodeMutationResponse(res, 'Inventory', (value) =>
      decodeChannelAllocations(value, slotId),
    );
  });
}
