// The back office's inventory client: one read and one write, both for the
// channel-allocation editor (TKT-244, ADR-057).
//
// DIRECT to inventory, not through the gateway. Both operations live under
// `/internal/`, which the gateway edge-denies by construction (ADR-002: the route table
// is the security boundary). Adding a named exception would publish capacity
// configuration to the public internet while granting this process nothing it does not
// already have — it can already open a socket to inventory on the container network. The
// credential is the boundary here; the network path is not. The staff refund reaches
// commerce exactly this way (TKT-194), and the operator channel read reaches catalog this
// way (TKT-236).
//
// A NEW credential rather than a reused one, which is the decision this ticket exists
// for. ADR-053 chose "no new credential" for catalog's operator read three days earlier,
// because that token could ALREADY create and update the channels it was then allowed to
// list — the allowance added amplification but no new capability class. The back office
// holds nothing for inventory, so reusing a catalog credential here would grant power
// across a service boundary and turn a catalog-token leak into an inventory-write leak.

import type { components } from './inventory-api-types.gen';
import type { ChannelAllocationSet } from './allocation-form';

export type StaffAvailability = components['schemas']['StaffAvailability'];
export type ChannelAvailability = components['schemas']['ChannelAvailability'];
export type ChannelAllocations = components['schemas']['ChannelAllocations'];

const INVENTORY_URL = process.env.INVENTORY_URL ?? 'http://localhost:8081';

/**
 * The back office's inventory credential (TKT-244, ADR-057).
 *
 * Read through a function rather than a module constant so a missing value fails on the
 * first call with a message naming the variable, instead of silently sending `undefined`
 * and surfacing as inventory's deliberately uninformative 401.
 *
 * Never `X-Internal-Token`: that one value opens every service's internal surface and is
 * deliberately withheld from this process (compose.yaml, and pinned by api.test.ts).
 */
function inventoryStaffCredential(): string {
  const token = process.env.INVENTORY_STAFF_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'INVENTORY_STAFF_WRITE_TOKEN is not set: the back office cannot edit channel allocations. ' +
        'It is generated by `make up` and supplied by compose.',
    );
  }
  return token;
}

const headerName = 'X-Inventory-Staff-Write-Token';

/** An inventory refusal the editor can attribute; see allocation-form.ts. */
export class InventoryApiError extends Error {
  constructor(
    public readonly status: number,
    message: string,
    public readonly code?: string,
    public readonly channel?: string,
  ) {
    super(message);
    this.name = 'InventoryApiError';
  }
}

async function refuse(res: Response): Promise<never> {
  let body: { error?: string; code?: string; channel?: string } = {};
  try {
    body = (await res.json()) as typeof body;
  } catch {
    // A body that is not JSON is not a refusal this client can attribute; the status
    // still has to reach the caller.
  }
  throw new InventoryApiError(
    res.status,
    body.error ?? `inventory answered ${res.status}`,
    body.code,
    body.channel,
  );
}

/**
 * The slot's staff availability: capacity, the derived counters, and one row per channel
 * allocation with its cap, window, gate, seller binding and CURRENT CONSUMPTION.
 *
 * The consumption is a condition of success for the editor — an operator lowering a cap
 * needs to see what the channel has already sold — and this is the only read that reports
 * it. It is also the read that makes a safe round trip possible: the write is a full-set
 * replace, so anything this read does not return is a field the next save destroys.
 */
export async function getStaffAvailability(
  slotId: string,
  organizerId: string,
): Promise<StaffAvailability> {
  const credential = inventoryStaffCredential();
  const url =
    `${INVENTORY_URL}/internal/slots/${encodeURIComponent(slotId)}/availability` +
    `?organizer_id=${encodeURIComponent(organizerId)}`;
  const res = await fetch(url, { headers: { [headerName]: credential } });
  if (!res.ok) return refuse(res);
  return (await res.json()) as StaffAvailability;
}

/**
 * Replace the slot's WHOLE allocation set, atomically, under the pool lock (ADR-024).
 *
 * There is no per-row save and there must not be one: the endpoint replaces the complete
 * desired state, so submitting one row would delete every other allocation. The editor
 * therefore always sends every row it read, including rows the operator did not touch.
 */
export async function replaceChannelAllocations(
  slotId: string,
  set: ChannelAllocationSet,
): Promise<ChannelAllocations> {
  const credential = inventoryStaffCredential();
  const res = await fetch(
    `${INVENTORY_URL}/internal/slots/${encodeURIComponent(slotId)}/channel-allocations`,
    {
      method: 'PUT',
      headers: { 'content-type': 'application/json', [headerName]: credential },
      body: JSON.stringify(set),
    },
  );
  if (!res.ok) return refuse(res);
  return (await res.json()) as ChannelAllocations;
}
